### ISSUE TITLE
AV at start 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#100]
Rio 10.3 
Update from 980 to 983

![image](https://user-images.githubusercontent.com/1270275/62524181-765b8e80-b835-11e9-94f0-6cce0e504ecb.png)

**Comment by shanzhashu** [comment]
Are you using 10.3.1? 
From 981, we support 10.3.2, but the RTL in 10.3.2 changes a lot from 10.3.1. CnWizards compiled by 10.3.2 cannot LOAD on 10.3.1, we're still doing the research the workaround about this problem.

**Comment by Sorien** [comment]
just 10.3 (my subscription ended before 10.3.1)

**Comment by Sorien** [comment]
any news?
