### ISSUE TITLE
脚本扩展专家，length函数无法接受一字符的参数

### ISSUE THREAD

**Issue by unjiang** [cnpack/cnwizards#101]
在使用脚本扩展专家时，length函数有时会无法通过，后来发现单一字符的参数不能通过，其他的参数可以通过。测试代码如下：
`program ScriptLength;

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ActnList, Buttons, ClipBrd, ComCtrls, ExtCtrls, ComObj, ExtDlgs, IniFiles,
  Menus, Printers, Registry, StdCtrls, TypInfo, ToolsAPI, CnDebug,
  RegExpr, ScriptEvent, CnCommon, CnWizClasses, CnWizUtils, CnWizIdeUtils,
  CnWizShortCut, CnWizOptions;

const
  c1 = 'a';
  s1 = 'abc大家好abc';

var
  i: Integer;

begin
  i := Length(s1);//可以通过
  showmessage(inttostr(i));
  i := Length(c1);//过不去，第一次运行提示：[Pascal Error] Unable to invoke Code Parameters due to errors in source code
  showmessage(inttostr(i));
end.
`

**Comment by unjiang** [comment]
Delphi5和XE7测试了都一样有问题。

**Comment by shanzhashu** [comment]
无法通过是指编译无法通过还是运行不了？您贴的错误信息是IDE关于代码自动完成的，需要看一下脚本窗口里的输出信息。

**Comment by unjiang** [comment]
可以编译。但是运行到这行就停下了。
脚本窗口中的信息如下：

正在编译...
编译成功
Type Mismatch 于 0.113

**Comment by shanzhashu** [comment]
经过分析，确定是Pascal脚本引擎语法分析的问题。它把const常量中单个字符识别为Char型，并且不支持Char型到String的默认转换。导致Length(Char)这样的调用出现类型不匹配。

如果是var C1: string;显式定义了类型为String，那无论它长度是1个字符还是多个，Length调用都能通过。
估计这个第三方的Pascal脚本引擎要增加Char型到String的默认转换比较难，只能接受这样的设定。
