### ISSUE TITLE
Delphi 10.3 Error opening Could not find CnWizards_D103R.dll

### ISSUE THREAD

**Issue by faktoral** [cnpack/cnwizards#102]
**CnWizards_1.1.8.984_Unstable**

<img src="https://i.ibb.co/z2K6n7M/Cn-Wizars-1.jpg" alt="Cn-Wizars-1" border="0">
<img src="https://i.ibb.co/CwNTrWV/Cn-Wizars-2.jpg" alt="Cn-Wizars-2" border="0">

**Comment by shanzhashu** [comment]
Our new nightly-build version now supports 10.3.2, but 10.3.2 complied CnWizards can not be loaded in 10.3.1 or below.
So we build another CnWizards DLL for 10.3.1，you can just run "Enable CnWizards" in CnPack IDE Wizards Menu from start menu, it will choose 10.3.1 one for your Delphi 10.3.1.

**Comment by faktoral** [comment]
@shanzhashu  Thank you for the information. Good work.
