### ISSUE TITLE
Syntax Highlighting with Korean character

### ISSUE THREAD

**Issue by PKDGOOD** [cnpack/cnwizards#114]
Syntax highlight after the Korean character overlaps the original source code.
I'm with CnWizard 1.1.9.991 at Delphi XE7

![cnWizSyntaxHighlight](https://user-images.githubusercontent.com/28861697/78951252-73bfe000-7b0c-11ea-9cb2-991b415708be.PNG)

**Comment by shanzhashu** [comment]
Oh. We don't know Korean language.
Could you send me a sample source file with Korean chars in it to debug?

**Comment by PKDGOOD** [comment]
It's not effects on compile or building. Just highlight looks awkward bit on code editor.
In my expectation, it might be caused by encoded byte size or something like that.

I uploaded sample source code and picture how it looks on my XE7 code editor below.
I hope it helps.

```
procedure korSampleProc();
var
  sEng, sKor : string;
begin
  sEng := 'This is Alphabets';
  sKor := '이 문장은 한글입니다';

  if sEng = '이 문장은 한글입니다' then
  begin
    // empty
  end
  else if sEng = 'This is Alphabets' then
  begin
    // empty
  end;
end;

  // Texts below are just for showing how hightlighter works awkward
  // It does not fit the Pascal grammar
  한글 begin end;
  Alphabet begin end;
  中文 begin end;
````

![korSampleProc](https://user-images.githubusercontent.com/28861697/78969753-b13f6000-7b42-11ea-87bb-2d76c0524d82.PNG)

**Comment by shanzhashu** [comment]
Thanks. I'll check it.

**Comment by shanzhashu** [comment]
Oh. I don't have Korean font. Only squares are shown in my Editor. ;-(
Could you send me the font file, too?

**Comment by shanzhashu** [comment]
I change system default language settings to "朝鲜语" and now I can display the correct chars with correct painting position.

![无标题](https://user-images.githubusercontent.com/3039960/79042118-9266c980-7c27-11ea-9702-d024381b4d78.png)

I think the problem comes from the font in your computer. Could you give the font name in your Delphi IDE Setting?

**Comment by PKDGOOD** [comment]
Sorry for I'm late.
I was using 'Courier New' which is default font on XE7. I changed to other fonts after checked your comments.
When I changed to some of fonts in the list, highlighter works very well as you commented.
From this situation, it seems that some of my Korean fonts have not good compatibility.
For now, I'll use font that cnWizard works well. 

Thank you for your consideration at this issue!

**Comment by shanzhashu** [comment]
OK. 
I guess maybe the font is in a "NOT Initilized" state or so in IDE when you first display Korean chars with "Courier New" font, so CnWizards can't paint them well. And it works fine when you re-select font and "initilize" it.
Anyway, now OK.

**Comment by PKDGOOD** [comment]
Thx! I'll try it.
