### ISSUE TITLE
代码格式化专家有一个语句过不去，请帮忙看看。

### ISSUE THREAD

**Issue by unjiang** [cnpack/cnwizards#116]
有一个函数，其中有一句：
str := Format('%s:%s(%s)', [uuPadSpace(Pplist[i]^.Name, 24), Pplist[i]^.PropType^^.Name, uugetTypeKind(Pplist[i]^.PropType^)]);
格式化后，变成了：
      str := Format('%s:%s(%s)', [uuPadSpace(Pplist[i]^.Name, 24), Pplist[i]^.PropType
        ^^.Name, uugetTypeKind(Pplist[i]^.PropType^)]);
然后再格式化，就提示：缺失有效符号，当前标识符：“^^”
第一次格式化正常，第二次却不行了，真奇怪。“^^”在一行中合法，变成一行开头就不合法了。

版本：Delphi5 + Ver: 1.1.8.980 Build 2019.07.01。下面是完成的函数：
procedure uuGetPropTree(aPTypeInfo: PTypeInfo; countProp: Integer; tree:
  TTreeView; node1: TTreeNode);
var
  Pplist: PPropList;
  i, j: Integer;
  str: string;
begin
  Pplist := nil;
  {$IFDEF Delphi7Up}
  if GetPropList(aPTypeInfo, Pplist) = 0 then
    Exit;
  {$ELSE}
  if GetPropList(aPTypeInfo, [tkUnknown, tkInteger, tkChar, tkEnumeration,
    tkFloat, tkString, tkSet, tkClass, tkMethod, tkWChar, tkLString, tkWString,
      tkVariant, tkArray, tkRecord, tkInterface, tkInt64, tkDynArray], Pplist) =
    0 then
    Exit;
  {$ENDIF}
  try
    for i := 0 to countProp - 1 do
    begin
      str := Format('%s:%s(%s)', [uuPadSpace(Pplist[i]^.Name, 24),
        Pplist[i]^.PropType
          ^^.Name, uugetTypeKind(Pplist[i]^.PropType^)]);
      with tree.Items do
      begin
        for j := Count - 1 downto 0 do
          if Item[j].Text = str then //uu,先删除子类中同名的属性
            Delete(Item[j]);
        AddChild(node1, str);
      end;
    end;
  finally
    FreeMem(Pplist);
  end;
end;

**Comment by shanzhashu** [comment]
感谢报告，因为^^在旧式的Pascal语法中也代表字符串，而我们的程序在^^之前有空白时误将其判断成了字符串，才有您提到的问题。

目前已修改，忽略^^之前的空白与换行。

**Comment by unjiang** [comment]
这么快就修复了！谢谢。
