### ISSUE TITLE
Formatter Issue

### ISSUE THREAD

**Issue by yesilcimenahmet** [cnpack/cnwizards#121]
Hi,

Please watch the video below. This problem is really annoying.

[Short video showing the problem](https://gofile.io/d/QhSjTg)

You can watch the video without downloading.

**CnPack Version Info:** Ver: 1.2.0.1006_Unstable Build 2020.07.15

Delphi 10.4

Thanks.

**Comment by shanzhashu** [comment]
See below page but can't download:

Name | f40c3898-cf0e-4cc2-bc21-92dce24754a7.webm
-- | --
Size | 761.0 KiB
MD5 | 85f358ed617fdd69ce8b12db9f8bbc62
Type | video/webm

**Comment by shanzhashu** [comment]
Or mail to our Email?   master@cnpack.org

**Comment by yesilcimenahmet** [comment]
Hi,

I sent video to mail address.

Thanks.

**Comment by shanzhashu** [comment]
See. I'll check it.

**Comment by shanzhashu** [comment]
Fixed. Please help to verify it in 1007? 

http://www.cnpack.org/downbuilds.php

Thanks for your report.

**Comment by yesilcimenahmet** [comment]
Hi,

Thanks for fix. New line issue is ok now but somethings goes wrong. I sent video to your mail.

For ex.

**Before**

`const
  ICON_INFO: TIconInfo = (hbmMask: 0; hbmColor: 0);`

**After**

```
const
  ICON_INFO: TIconInfo = (    hbmMask:     0;     hbmColor:     0
  );
```

**Comment by cnpack** [comment]
Got it. Fixed in 1008.
Please try again?

**Comment by yesilcimenahmet** [comment]
I am sorry but worse now :)

[Video](https://gofile.io/d/jgVoNW)

I also sent it to mail address.

**Comment by cnpack** [comment]
Oh. Could you provide a snapshot about your Code Formatter Setting Dialog? I'll check some options about it.

**Comment by yesilcimenahmet** [comment]
Sure,

[Image](https://i.ibb.co/mc5CK83/code-formatter-settings.png)

**Comment by yesilcimenahmet** [comment]
Hi,

Did you fix it? Can you publish for nightly build?

Thanks.

**Comment by yesilcimenahmet** [comment]
any fixing ??

**Comment by shanzhashu** [comment]
Wierd, according to your settings this bug should already be fixed in my workstation.

Could you check the CnFormatLib.dll and CnFormatLibW.dll's File Version in its Properties dialog in  CnWizards installation Directtory in Windows Explorer?

**Comment by yesilcimenahmet** [comment]
No problem occurred again with 1008 version.

The version number of both 1.2.0.1008

Please watch the video below to see the problem.

[Video](https://gofile.io/d/15IzxO)

**Comment by yesilcimenahmet** [comment]
Please fix it. 

New lines are added continuously while each format operation is done. I'm tired of cleaning them.

**Comment by shanzhashu** [comment]
OK. Please try our 1009 nighly-build version?

**Comment by yesilcimenahmet** [comment]
Oh thanks. It worked now. Thank a lot!
