### ISSUE TITLE
[Code Formatter] property with &

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#124]
```pascal
  TFoo = class()
  public
    constructor Create();
    property &Set: TFaa read GetFaa;
  end;
```

after format
```pascal
  TFoo = class()
  public
    constructor Create();
    property&Set: TFaa read GetFaa;
  end;
```

will remove space between `property` and `&`, its weird cause delphi will compile such code

**Comment by shanzhashu** [comment]
OK. Fixed.

**Comment by Sorien** [comment]
it seems to be fixed but the last commit created another bug

```pascal
type
  TFOO = class
  public
    function &set(): TFaa
    property &set: TFaa read GetFaa;
  end;
```

after
```pascal
  TFOO = class
  public
    function  &set(): TFaa
    property &set: TFaa read GetFaa;
  end;
```

it adds extra space after `function`

**Comment by shanzhashu** [comment]
Oh, my fix was wrong. Now I fix again.

if "&" without prefix space in any other place, please tell me again. I'll fix them.

**Comment by Sorien** [comment]
seems to be ok, thx

**Comment by DelphiWorlds** [comment]
I am using Ver 1.2.0.1022_Unstable Build 2021.02.26, and the formatter still has issues with `&`:

![image](https://user-images.githubusercontent.com/22670829/124404941-2e747780-dd7c-11eb-902c-eb4c483be5b1.png)

**Comment by shanzhashu** [comment]
Will fix in next nightly-build version.
