### ISSUE TITLE
[Code Formatter] Comment after else

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#126]
we are using something like

```pascal
procedure Foo();
begin
  // comment
  if Test then
    Test()
  else
    // comment
    if Test then
        Test;
end;
```
or 
```pascal
procedure Foo();
begin
  // comment
  if Test then
    Test()
  else // comment
    if Test then
        Test;
end;
```

but after formatting else part will have wrong indent
```pascal
procedure Foo();
begin
  // comment
  if Test then
    Test()
  else
    // comment
if Test then
    Test;
end;
```

**Comment by shanzhashu** [comment]
Partly fixed but still have problem about indent spaces.

**Comment by shanzhashu** [comment]
Fix again. But a minor issue remains:

We treat "else if" as a whole part even though the line comment breaks it, so the next indent is compared to "else“, not the "if", so the result now is:

  // comment
  if Test then
    Test()
  else // comment
    if Test then
    Test;

It's not easy to align and indent from "if" in "else if" compare to "else"...

**Comment by Sorien** [comment]
I thought that it would be something simple but now I understand will try to not use it at our side
