### ISSUE TITLE
Delphi 10.4.1 Wrong Lines (CnWizards_1.2.0.1018) 

### ISSUE THREAD

**Issue by faktoral** [cnpack/cnwizards#130]
<a href="https://ibb.co/Y4gc048"><img src="https://i.ibb.co/gbYS4bw/Cn-Pack-Wrong-Line.jpg" alt="Cn-Pack-Wrong-Line" border="0"></a>

**Comment by shanzhashu** [comment]
Seems the wrong line comes from Delphi itself?

You can disable it from Tools, Options, User Interface, Editor Options, Color, Structural Highlighting.

**Comment by faktoral** [comment]
@shanzhashu 
Thank you. problem is solved.
