### ISSUE TITLE
本工具只支持非嵌入模式的 VCL 设计期窗体

### ISSUE THREAD

**Issue by reghtml** [cnpack/cnwizards#131]
delphi 10.4 中，之前一直使用正常

后来发现在添加控件的时候，突然发现控件不会自动重命名了，然后我点开 
![image](https://user-images.githubusercontent.com/15364651/106230707-11ff6c80-622b-11eb-8932-280bb652bed4.png)

提示如下错误

![image](https://user-images.githubusercontent.com/15364651/106230689-0744d780-622b-11eb-8e87-b427dba4a799.png)

之前好好的，我后来卸载了cnwizards ，然后重新换了一个目录，又安装，就这样子了

期间我还安装了jedi的jvcl控件，不知道是否与这个有关

**Comment by shanzhashu** [comment]
您提到的这个自动重命名的功能属于“组件前缀专家”，可以在菜单里找“组件前缀专家”中去设置。

**Comment by reghtml** [comment]
谢谢，我找到了这里，原来这个状态是禁用了，我设置为启用状态就可以了
![image](https://user-images.githubusercontent.com/15364651/106262975-bbac2100-625e-11eb-8ed6-5e931bec102e.png)
