### ISSUE TITLE
代码编辑器扩展-禁止光标超出行尾-功能失效

### ISSUE THREAD

**Issue by reghtml** [cnpack/cnwizards#132]
代码编辑器扩展-【禁止光标超出行尾】-功能失效
我是在delphi 10.4.1 的环境中，开启或关闭此功能，没有生效

![image](https://user-images.githubusercontent.com/15364651/106231016-a8cc2900-622b-11eb-80b9-e21899dcac49.png)

希望修复一下这个功能

**Comment by shanzhashu** [comment]
是偶尔不生效，还是一直就无法生效、随意点击光标都能超出行尾？

**Comment by reghtml** [comment]
是的，100%不生效，随便点击光标都不会在代码的最尾部，而是光标停留在鼠标点击位置的空白处
据别人测试也是这样子

**Comment by shanzhashu** [comment]
此功能确实失效了，目测10.4可能有意干扰了此功能，感觉只能暂时禁用了。

**Comment by shanzhashu** [comment]
已禁用此功能。
