### ISSUE TITLE
IdeGetEditorSelectedLines & IdeSetEditorSelectedLines changes context

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#134]
i'm using simple script to replace some code patterns
```pascal
program ReplaceFieldByName;

uses
  Windows, SysUtils, Classes, CnCommon, CnWizIdeUtils, RegExpr;

var
  Lines: TStringList;
  I: Integer;
begin
  Lines := TStringList.Create;
  try
    if IdeGetEditorSelectedLines(Lines) then
    begin
//      for I := 0 to Lines.Count - 1 do
//        Lines[I] := ReplaceRegExpr('(?i)\.FieldByName\((''[a-zA-Z0-9_]+'')\)', Lines[I], '[$1]', True);

      IdeSetEditorSelectedLines(Lines);
    end;
  finally
    Lines.Free;
  end;
end.
```

but simple IdeGetEditorSelectedLines IdeSetEditorSelectedLines cals will change source like

```pascal
    LabCount := 'Počet označených záznamov: ' + IntToStr(SelectedIds.Count);
```

will be changed to 

```pascal
    LabCount := 'Pocet oznacených záznamov: ' + IntToStr(SelectedIds.Count);
```

it strips some diacritics `Počet` -> `Pocet` and so on file and script are in *UTF-8 with BOM*

**Comment by shanzhashu** [comment]
Could you tell me what's your Delphi Version?

**Comment by Sorien** [comment]
10.3.3

**Comment by shanzhashu** [comment]
See.  We found an unessesary Unicode to Ansi conversion in our IdeSetEditorSelectedLines routine, which causes chars lost.
It's fixed at next nightly-build version.

**Comment by shanzhashu** [comment]
1020 nightly-build version comes out. Please verify it.

**Comment by Sorien** [comment]
thx, works great!
