### ISSUE TITLE
Code formatter initialization 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#135]
it's a very low priority but I noticed that 

```pascal
initialization
  Rights
    .Section('foo')
    .RegisterRight('faa')
end.
```

after formatting it will add new line before end. each time 

```pascal
initialization
  Rights
    .Section('foo')
    .RegisterRight('faa')



end.
```

`;` after the last statement will fix it

**Comment by shanzhashu** [comment]
OK. Fixed in 1020 nightly-build version.

**Comment by Sorien** [comment]
hmm, I see no difference, it still adds newlines in 1020

**Comment by shanzhashu** [comment]
Oh, some fix missing. Will done at next version.

**Comment by shanzhashu** [comment]
1023 will fix this problem.

**Comment by shanzhashu** [comment]
Already fixed in our new nightly-build versions.

**Comment by Sorien** [comment]
I'm not able to try it right now, will close and reopen if needed, thanks for fixes
