### ISSUE TITLE
Please support bidi for strings and comments in code editor

### ISSUE THREAD

**Issue by DelphiMan68** [cnpack/cnwizards#136]
Hello and thank you for your greate tool
In delphi IDE by default right to left languages not supporting.
I want describe this issuse and please support this feature in cnpack wizard.

1- strings can not show properly in code editor. this is wrong:
![2021-02-22_13-32-10](https://user-images.githubusercontent.com/10184622/108692965-89ff4080-7512-11eb-9d6c-3f4f82a527cb.png)
and It must be like this:
![2021-02-22_13-35-11](https://user-images.githubusercontent.com/10184622/108693354-faa65d00-7512-11eb-977d-089fae8728cc.png)

2- also, we have this problems for comments in code editor!

Notice that, if strings starts with a right to left language character then It must detect as right to left language.
this is very important feature for some languages like persian and arabic and etc.

thank you for greate and valuable works :)

**Comment by shanzhashu** [comment]
I know the requirement. But we're only wizards, it's almost impossible for us to change the internal behavior of Code Editor in Delphi IDE itself.
We can only paint some additional lines or chars on editor.
