### ISSUE TITLE
Delphi 10.4.2编辑器不显示顶部函数列表框了

### ISSUE THREAD

**Issue by lickyzh** [cnpack/cnwizards#137]
安装后，编辑器滚动两下就不显示了，点顶部菜单的Component->Install Package，然后取消就能恢复，但是动不动就又没了。
彻底关闭cnwizard之后就好了。期待修复！

应该这样显示函数列表：
![QQ图片20210225165409](https://user-images.githubusercontent.com/24434674/109128103-1bc4b300-778a-11eb-86e9-bc343e65a65c.png)

可是动不动函数列表就框就不见了
![QQ图片20210225165414](https://user-images.githubusercontent.com/24434674/109128113-1ebfa380-778a-11eb-82a1-4747e05dc472.png)

**Comment by shanzhashu** [comment]
比较神奇。烦请下载最新的1022试一试看看有无此问题？
http://www.cnpack.org/downbuilds.php?lang=zh-cn

**Comment by lickyzh** [comment]
已经安装最新版1029，但是问题依旧，目前找到了问题原因，是代码编辑器扩展造成的，只要关闭代码编辑器扩展就可以显示函数列表了。

![image](https://user-images.githubusercontent.com/24434674/115366511-fc7d5b80-a1f7-11eb-9fe4-1d48da397b18.png)
![image](https://user-images.githubusercontent.com/24434674/115366651-17e86680-a1f8-11eb-8752-504f34414e6c.png)
![image](https://user-images.githubusercontent.com/24434674/115366762-29ca0980-a1f8-11eb-8c63-b686fec5033d.png)

**Comment by shanzhashu** [comment]
您可以在重新启用”代码编辑器扩展“后，在任意一个源码页面里按Ctrl+D弹出函数过程列表窗口，在该窗口上的齿轮按钮上点击以启用CnPack的函数列表工具栏。
