### ISSUE TITLE
[Delphi 10.4.2] Bug in source highlight when Editor rendering style is set to Smooth Wave

### ISSUE THREAD

**Issue by LukaszDemczuk** [cnpack/cnwizards#138]
Hi,

If in Delphi 10.4.2 I have **Editor rendering style** set to **Smooth Wave**: 

![image](https://user-images.githubusercontent.com/47881921/109283385-064d9880-781f-11eb-83ef-d0832347196a.png)

then source highlight doesn't work or is working wrong:

![image](https://user-images.githubusercontent.com/47881921/109284057-b9b68d00-781f-11eb-8912-f9c605366db0.png)

For other **Editor rendering style** is ok.

**Comment by shanzhashu** [comment]
Seems this new feature will change Editor Paint settings and affect our Highlight feature.
I'll do some research on it.

**Comment by shanzhashu** [comment]
Root cause found. When Smooth Wave mode is selected, there's additional 3 pixels offset for each line height in Editor.
We must also add 3 pixels for our painting accordingly.

Thank you for your report.

**Comment by shanzhashu** [comment]
Fixed. Please try our latest nightly-build 1023?

http://www.cnpack.org/downbuilds.php?lang=en

**Comment by LukaszDemczuk** [comment]
Now is ok. Thanks.
