### ISSUE TITLE
Shortcut to move line down doesn't work

### ISSUE THREAD

**Issue by delmohf** [cnpack/cnwizards#139]
Hi guys:

I don't know why but the well-known shortcut Ctrl+Alt+Shift+D to move selected lines down has stopped working. I can't find this functionality on your add-on UI so that I can change the shortcut or maybe reset it.

Any idea?

My apologize if I'm missing something.

Thanks!

**Comment by shanzhashu** [comment]
In the Editor FlatButton Dropdown menu. "Others"->"Options", there's a dialog to customize shortcuts.

**Comment by delmohf** [comment]
There is no reference to move line up/down shortcut in that dialog, take a look to the screenshot

![image](https://user-images.githubusercontent.com/11967822/112724580-5601ab80-8f14-11eb-91dc-2e7e0ad0ab3d.png)

I'm using the last nightly build 1.2.0.1027_Unstable

**Comment by shanzhashu** [comment]
The entry is as the screenshot:
![未标题-1](https://user-images.githubusercontent.com/3039960/112725628-2e323800-8f54-11eb-920c-3307b97ed6c5.png)

**Comment by delmohf** [comment]
Great! Thanks for your time!
