### ISSUE TITLE
Shortest delay for "Background Highlight Current Identifier"

### ISSUE THREAD

**Issue by ManD12** [cnpack/cnwizards#141]
Please set in IdeEnhancements/CnSourceHighlight.pas
 FCurrentTokenDelay := 500; {now hardcoded}
to new:  FCurrentTokenDelay := csShortDelay;

Or totaly do not use timer for Highlight Current Identifier at Cursor. It not use after arrow keys, PgUp, PgDn (not working immediately after F3 or Ctrl+Left, Ctrl+Left+Up). 
Or make this timer delay configurable.

Thank you

**Comment by shanzhashu** [comment]
OK. Change to csShortDelay to decrease the delay time for cursor moving.
