### ISSUE TITLE
IDE sent to background when select file with List Unit from Project wizard

### ISSUE THREAD

**Issue by delphicz** [cnpack/cnwizards#142]
When select unit from List Unit wizard IDE is send to back to background or lost focus (if is only application).

**Comment by delphicz** [comment]
D10.4.2, CnPack 1.2.0.1024_Unstable Build 2021.03.17

**Comment by shanzhashu** [comment]
Oh. I should have fixed this problem in 1024 yesterday but don't know why it still exists......

**Comment by delphicz** [comment]
Oh, my "c:\Program Files (x86)\Embarcadero\Studio\21.0\bin\coreide270.bpl" was 27.0.40650.4203 (not 40680), I apologize. Redownloaded instalation and it is OK.
