### ISSUE TITLE
cnwizards do not load after installing 1.2.0.1027 over 1.2.0.1025

### ISSUE THREAD

**Issue by LingamYoni** [cnpack/cnwizards#144]
![2021-04-01_100107](https://user-images.githubusercontent.com/40486018/113256672-2ff05880-92d2-11eb-9d7e-c144d3306429.jpg)

**Comment by shanzhashu** [comment]
Thanks for your report. It's a new bug introduced last week. We'll fix it soon.

**Comment by LingamYoni** [comment]
Fixed in 1.2.0.1028, thanks.
