### ISSUE TITLE
XE2 Dll project , not find implementation

### ISSUE THREAD

**Issue by dbyoung720** [cnpack/cnwizards#146]
XE2 Dll project , not find implementation。1.2.0.1031_Unstable Build 2021.05.08
![err](https://user-images.githubusercontent.com/11304997/118768377-8250fd00-b8b1-11eb-8b44-187b37275a9f.png)

**Comment by shanzhashu** [comment]
OK. we found this problem and fixed. Please wait for the next 1032 version.

**Comment by dbyoung720** [comment]
10.4 下 exe 工程也会出现这样的问题。

**Comment by shanzhashu** [comment]
1032bui出来了烦请下载验证一下？

**Comment by dbyoung720** [comment]
XE2、XE10.4，测试通过。OK。
但 函数过程列表...，变成删除行了。XE2、XE10.4 都是的。
