### ISSUE TITLE
函数过程列表...，变成删除行了

### ISSUE THREAD

**Issue by dbyoung720** [cnpack/cnwizards#147]
函数过程列表...，变成删除行了。
XE2、XE10.4 都是的。WIN10X64。
点击菜单没有问题。当按快捷键时，就变成删除行了。

**Comment by shanzhashu** [comment]
开始菜单里用专家包设置导入导出工具重置一下选项看看？
不确定被谁抢掉了快捷键。

**Comment by dbyoung720** [comment]
我测试了一下，用默认的 CTRL+D 是没有问题的。
换成 Ctrl+Shift+D，变成删除上一行。
换成 Ctrl+Alt+D，变成回车了。

换成 1.1.9.991 正式版，CTRL+D、Ctrl+Shift+D、Ctrl+Alt+D 都是没有问题的。
应该不是注册键的问题。应该是代码BUG。

**Comment by shanzhashu** [comment]
默认的 CTRL+D没问题就好。

Ctrl+Alt+D是“在当前位置重复”的功能，见选中一批文字时左边浮动按钮的下拉菜单里。

Ctrl+Shift+D的问题我查查。

**Comment by dbyoung720** [comment]
看见了。
那么，在用户设置快捷键时，应该检查一下快捷键设置的可用性。
否则用户设置了，当然认为是可用的。事实上不可用，或不是用户想要的结果。

**Comment by shanzhashu** [comment]
有道理，我们在各处设置快捷键时加一层检测提示试一试。

**Comment by shanzhashu** [comment]
1033版在各处设置快捷键时增加了检测提示。

**Comment by dbyoung720** [comment]
我将默认的 CTRL+D，换成 CTRL+SHIFT+D，没有错误提示。按下 CTRL+SHIFT+D 依然是删除行。
然后，我将 CTRL+SHIFT+D 换回 CTRL+D，提示已经注册过。点确定。恢复正常功能。
XE10.4，1033，WIN10X64下测试。

**Comment by shanzhashu** [comment]
1033判断重复的搜索范围不够，CTRL+SHIFT+D是直接注册的快捷键，不在我们判断的整个Action中。新版本会把直接注册的快捷键也加上。
