### ISSUE TITLE
TFileOpenDialog string builder

### ISSUE THREAD

**Issue by GrooverMD** [cnpack/cnwizards#150]
Hi,

Great software by the way. I have a feature request. Can you include a TFileOpenDialog file types string builder to take the drudgery out of manually adding this? I would of thought Embarcadero could of added a wizard to achieve this already. I think it would be a great addition to CnPack.

Cheers.

**Comment by shanzhashu** [comment]
Thank you for your suggestion. The problem is, what's a good designer for a opendialog file types, especially should be better than IDE's string grid itself.

**Comment by GrooverMD** [comment]
Lui,

Thank you for your reply. I will mock up a designer. I don’t have the technical knowledge to implement this my self. ☹

Regards,
Mark.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cnpack** [comment]
No mock up designer.
