### ISSUE TITLE
Clean Temporary Files not working as expected

### ISSUE THREAD

**Issue by fabvit** [cnpack/cnwizards#152]
Hi,
I am on Delphi 10.4 Sydney and after installing latest night build (CnWizards_1.2.0.1048_Unstable) the Clean Temporary Files is not working as expected.
 
Basically it seems that Clean Temporary Files does not scan sub directories of of project's folder in search for temporary files.
 
I have the following directory structure:

    C:\1DP\MyProject\ -> Main project folder
    C:\1DP\MyProject\Win32\Debug\Dcu -> contains temporary files for Debug build
    C:\1DP\MyProject\Win32\Release\Dcu -> contains temporary files for Release build

Until version CnWizards_1.2.0.1040_Unstable, when I click the Next button on the Clean Temporary Files dialog, I can see it correctly scans for sub folder, successfully finding all temporary files in the Dcu sub folders.
 
With version CnWizards_1.2.0.1048_Unstable, when I click the Next button on the Clean Temporary Files dialog, it does not scans Dcu folders. 
 
So I had to revert to CnWizards_1.2.0.1040_Unstable.
 
Does someone is having a similar issue?

**Comment by shanzhashu** [comment]
Thanks for your report. I'll check it.

**Comment by fabvit** [comment]
Hi Liu: thank you so much for digging in to my issue!

In the mean time I have also logged it in to the GitHub issue tracker.



Thank you again.



Regards



--
Fabio Vitale

***@***.***



From: "Liu Xiao ***@***.***)" ***@***.***>
To: cnpack/cnwizards ***@***.***>
Cc: fabvit ***@***.***>,  Author ***@***.***>
Date: Wed, 08 Sep 2021 01:47:20 -0700
Subject: Re: [cnpack/cnwizards] Clean Temporary Files not working as 
expected (#152)



ATTENZIONE: Questa email è originata all’esterno di Envisioning. Non 
cliccare sui collegamenti né aprire gli allegati se non riconosci il 
mittente e sai che il contenuto è sicuro.







Thanks for your report. I'll check it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 

Le informazioni contenute nel presente documento sono riservate all'uso esclusivo del destinatario e possono essere soggette alla normativa sulla  privacy ed al segreto professionale. Se il lettore non e' l'inteso destinatario, si notifica che non deve utilizzarlo, riprodurlo,  diffonderlo, copiarlo in qualsiasi forma o agire facendovi affidamento. Se  Lei ha ricevuto questo messaggio per errore, e' pregato di distruggerlo, anche in ogni sua copia, ed avvisare immediatamente ENVISIONING al seguente numero +39 06-8632.5304 o all'indirizzo ***@***.*** La riservatezza delle informazioni e' tutelata indipendentemente da errori  nella trasmissione di questo messaggio.  L'integrita' e la sicurezza di questo messaggio non possono essere  garantite su Internet. Qualsiasi parere espresso in questo messaggio e' opera esclusiva del mittente e non rappresenta quello di ENVISIONING,  salvo quando il messaggio in modo specifico statuisce diversamente ed il  mittente e' autorizzato ad affe
 rmare che i pareri espressi sono di ENVISIONING. ENVISIONING S.R.L. si riserva il diritto di monitorare tutte le comunicazioni via e-mail effettuate tramite la propria rete. 
---
The information in this message is sent by a professional or His/Her agent, is intended to be confidential and for the use of only the individual or entity named above. If the reader of this message is not the intended recipient, You are notified that retention, dissemination, distribution or copying of this document is strictly prohibited. If you have received this message in error please delete it and any copies of it and notify ENVISIONING immediately at this number +39 06-8632.5304 or address ***@***.*** No confidentiality or privilege is waived or lost by any mistransmission. The integrity and safety of this message cannot be guaranteed on Internet. Any views expressed in this message are solely those of the individual sender and do not represent those of ENVISIONING, except where the message specifically states otherwise and the sender is authorized to  state them to be the views of ENVISIONING. ENVISIONING S.R.L. reserve the right to monitor all e-mail communications 
 through its networks.

**Comment by shanzhashu** [comment]
I have a question. Do you check the checkbox in each directory in list? Checked means recursive, to search the sub-folders.

**Comment by fabvit** [comment]
Hi Liu,
In the list, I only have one entry: 

C:\1DP\MyProject\ -> Main project folder

and yes it is checked

**Comment by shanzhashu** [comment]
OK, another question, Is the checkbox "Keep Obj/Dcu Files when NO Same Source File Exist" Checked? If checked, the dcu files which has no the same source in the same directory will be kept.

**Comment by fabvit** [comment]
"Keep Obj/Dcu Files when NO Same Source File Exist" is *NOT* checked. So I reverted from CnWizards_1.2.0.1048_Unstable to CnWizards_1.2.0.1040_Unstable and everything works as expected.

Please note, if that can be of some relevance, that each time I install CnWizard I do not uninstall any previous version. I simply install over the existing CnWizard. Is that correct? or do you suggest instead to first uninstall existing CnWizard?

**Comment by fabvit** [comment]
How can I try to perform a clean install? I mean, what are the folders do I need to clean in order to clean any existing CnWizard settings?

**Comment by shanzhashu** [comment]
If want to reset CnWizards settings, you can run "Config I/O" Tool in CnPack's start Menu.
It has an option to reset  all settings of CnWizards.

But I think this problem should have no relations with 'Old' settings when overlay installing.
Now I still can't find the clue. 

You say 1040 is OK but 1048 not. Because there're too many changes before 1048 and 1040, could you help to try 1044 ?

**Comment by fabvit** [comment]
1. OK, thanks, I will wait resetting all settings  of CnWizards.
2. Tried version 1044 and it works *fine* as expected (as version 1040). Tell me if yon would like I try other versions.

**Comment by shanzhashu** [comment]
OK. I found a related change after 1044. Could you also try 1045? If 1045 is OK, I'll catch the point.

**Comment by fabvit** [comment]
Tried version 1045 and Clean Temporary Files is **NOT** working as expected.
Also I noticed the version 1045 is the first version where there is the new checkbox "Keep Obj/Dcu Files when NO Same Source File Exist".
I tried both with Keep Obj/Dcu Files when NO Same Source File Exist" **NOT** checked and checked and either way is **NOT** working as expected.
Tell me if you need I perform some more testing: I am glad to help you.

**Comment by shanzhashu** [comment]
Seems the new checkbox is "Remove __history and __recovery Directory"?

**Comment by fabvit** [comment]
Sorry for my confusion, you are absolutely right: in version 1045 the new checkbox is "Remove __history and __recovery Directory".

**Comment by fabvit** [comment]
Just downloaded and tested version CnWizards_1.2.0.1049_Unstable: thank you so much, problem fixed!

**Comment by shanzhashu** [comment]
Just upload it and you try so fast. Thank you for your report and help.

**Comment by fabvit** [comment]
I really appreciate your work!
