### ISSUE TITLE
[Feature request] Formatter correct unit and Type name 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#16]
like
```
uses
  dialogs;
```
after reformat 
```
uses 
  Dialogs;
```

**Comment by shanzhashu** [comment]
This feature is ready but not in Setting Dialog. When enabled, it will retrieve IDE's internal symbols to do the correction.

Open Registry and set
HKEY_CURRENT_USER\Software\CnPack\CnWizards\CnCodeFormatterWizard\UseIDESymbols to 1 and restart Delphi, we can see this feature works.

**Comment by Sorien** [comment]
i can't set it manually everytime program starts it will reset it to 0

**Comment by shanzhashu** [comment]
Please close IDE and run regedit to set this value to 1 for this value will be over written when IDE exits. Could you try it again?

**Comment by Sorien** [comment]
seems to be working very well, could you move that settings to code formatter settings dialog or make it permanent.

**Comment by shanzhashu** [comment]
OK. I'll move it to visible.
