### ISSUE TITLE
Code Formatter error, "Symbol Expected"

### ISSUE THREAD

**Issue by JohnnyMarauder** [cnpack/cnwizards#162]
Using the CnPack Code Formatter, I am getting the error:

Format Error (135,4): Symbol Expected.
Current: ";"

The internal Delphi XE formatter is fine.  I am using DevExpress and the relevant location is the last semicolon inside the final {$ENDIF} of an {$IFDEF DXSKINDYNAMICLOADING}  {$ELSE}  {$ENDIF}  

Attached is the Main.pas that it is erroring on.  This is with the current nightly build _1097_Unstable

[Main.zip](https://github.com/cnpack/cnwizards/files/9128093/Main.zip)

**Comment by dreamnyj** [comment]
Very common problems, sometimes really helpless. The accessories provided are very good.

**Comment by shanzhashu** [comment]
There's no good way to resolve complex {$IFDEF} {$ELSE} {$ENDIF} entirely.

You can try to modify an option in our Formatter Settings Dialog:

Compiler Directive: Change from "Treat as Comment" to "Process First Branch Only".
