### ISSUE TITLE
Converting VCL.Images.pngImage to FMX

### ISSUE THREAD

**Issue by Makhaon** [cnpack/cnwizards#166]
When CnPack do convrting to FMX it simply rename VCL.Images.pngImage to FMX.Images.pngImage. But such module does not exists in the FMX. And it not needed at all.
Is better just remove VCL.Images.pngImage from uses clause while do convrting.

**Comment by shanzhashu** [comment]
Thank you for your nice suggestion.
We'll remove this used unit in next nightly-build version.
