### ISSUE TITLE
F2 shortcut not working. Save meu item does.

### ISSUE THREAD

**Issue by hafedh-trimeche** [cnpack/cnwizards#168]
Hello,

Please note that the save action works only from the menu item but doesn't from the F2 shortcut.

How to reconfigure the F2 shortcut under a Classic IDE?

3rd Checkbox unchecked but clicking F2 (Keyboard) not saving editor's content! Clicking F2 (Mouse cursor) saved the file.

![image](https://user-images.githubusercontent.com/988584/220284442-7f76fe03-8b7a-423b-b52b-c2eee909730f.png)

Best regards.

**Comment by shanzhashu** [comment]
There's 2 feature which maybe occupy F2 key in CnWizards. One is the "F2 Rename Identifier" in Editor, the other is "F2 Rename Selected Component" in Designer.

But the 2nd option is not public for setting yet. Now we make it public and build a new nightly-build version 1120 at:

http://www.cnpack.org/downbuilds.php

You can install it, "CnPack" menu -> "Prefix Wizard" -> "Setting" Button -> "Use F2 Key to Rename..." CheckBox to try it again.
