### ISSUE TITLE
[Formatter] Bugs and lack of options

### ISSUE THREAD

**Issue by mgcd-jed** [cnpack/cnwizards#172]
```
uses
  {$ifdef MYVAR}
  Unit1,
  Unit2;
  {$endif}

  {$ifdef MYOTHERVAR}
  Unit1;
  {$endif}
```
Will raise an error, whether Compiler Directives are set to "Process First Branch Only" or to "Treat as Comment".

Comment between an `else` and an `if` such as `end { comment } if` will reset the indent of the `if` to zero.

---

In addition to this, there seems to be very few options, for example I'd like `end else if (something) then begin` to be on one line but that doesn't seem possible.

This is annoying, because the Delphi formatter has bugs CnPack doesn't have, and CnPack has bugs the Delphi formatter doesn't have x) Is there any intention of working on the formatter ? If not I'll just move on.

**Comment by cnpack** [comment]
Oh, we can't deal with your code piece for our parser's limitation.

**Comment by mgcd-jed** [comment]
Ah well. For future devs : the formatter from GExperts handles this, so I've been using it 👍
