### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by BoscoBecker** [cnpack/cnwizards#173]
Hello, I really admire your work and would like to know. How difficult is it to create a minimap, using the SynEdit, minimap component in the editor, as it has a demo: https://github.com/SynEdit/SynEdit/tree/master/Demos/MiniMap . And if it is possible where should I start to develop. Or is this on your roadmap? Thank's.

**Comment by shanzhashu** [comment]
Don't know about MiniMap. Is it related to Delphi IDE or any Wizard?

**Comment by BoscoBecker** [comment]
About minimap in Delphi through CNPack.
