### ISSUE TITLE
[Feature Request] Calculate record size

### ISSUE THREAD

**Issue by chicknsoup** [cnpack/cnwizards#174]
Hello,
I'm not sure if it's possible or not but I would like to request an editor enhancement like this: When hovering the mouse over a record, a popup (like code insight) appears and shows record size (in bytes)

Thank you.

**Comment by shanzhashu** [comment]
Oh, It's hard to calculate record size correctly in source level.
Only SizeOf() in runtime works.

**Comment by chicknsoup** [comment]
Can we do something like a record parser that parses record declaration text and calculates the size with a dictionary lookup (Integer:4; Int64:8, etc.)?

**Comment by cnpack** [comment]
No way without compiling.
