### ISSUE TITLE
Interaction between CnPack IDE Wizards (CnWizards) and Punto Switcher/Caramba Switcher.

### ISSUE THREAD

**Issue by mioram** [cnpack/cnwizards#176]
Greetings.

Thank you for a wonderful product!

I use C++Builder 5 and CnPack IDE Wizards (CnWizards), and also Punto Switcher/Caramba Switcher.
https://ru.wikipedia.org/wiki/Punto_Switcher
https://ru.wikipedia.org/wiki/Caramba_Switcher

Punto Switcher/Caramba Switcher is a program for switching the layout of the entered text Russian/English.

> The main purpose of the program is to increase productivity and convenience when working with a computer. Working in the background, Punto Switcher performs a statistical analysis of the sequences of entered characters of a word, and if the combination of letters turns out to be atypical for the language in which the characters are entered, Punto Switcher switches the input language, erases what has been typed, emulating pressing the ← Backspace key, and re-enters the text already with the correct keyboard layout.

I do not use automatic switching, but only use manual switching of the entered text using the Pause / Break hot key.

But in C++ Builder 5 with CnPack IDE Wizards (CnWizards) installed, passing the Pause/Break hotkey to Punto Switcher/Caramba Switcher programs does not work. And apparently CnPack IDE Wizards (CnWizards) blocks monitoring of input text by other programs.

Is there anything you can do about this to make both programs work together (very handy!)?

**Comment by cnpack** [comment]
We‘re not sure about this conflict, we'll check it.

**Comment by mioram** [comment]
Hello.

Yes, that's exactly what I meant.

In C++Builder 5, the problem persists if you turn off "Input Helper". And if you remove cnwizards, then Punto Switcher/Caramba Switcher works fine.

And in Delphi 7 - everything works fine cnwizards + Punto Switcher/Caramba Switcher.
And in RAD Studio 11.3 (C++ Builder) it also works fine.
