### ISSUE TITLE
[Question] How I can run command file from Script 

### ISSUE THREAD

**Issue by dshumko** [cnpack/cnwizards#179]
I would like to run external script on event Before Compile.
How I can do it?

for example: ExeAndWait(ExtractFilePath(Application.ExeName) + 'BeforeCompile.bat', SW_HIDE);

```
function ExeAndWait(ExeNameAndParams: string; ncmdShow: Integer = SW_SHOWNORMAL): Integer;
var
    StartupInfo: TStartupInfo;
    ProcessInformation: TProcessInformation;
    Res: Bool;
    lpExitCode: DWORD;
begin
    with StartupInfo do //you can play with this structure
    begin
        cb := SizeOf(TStartupInfo);
        lpReserved := nil;
        lpDesktop := nil;
        lpTitle := nil;
        dwFlags := STARTF_USESHOWWINDOW;
        wShowWindow := ncmdShow;
        cbReserved2 := 0;
        lpReserved2 := nil;
    end;
    Res := CreateProcess(nil, PChar(ExeNameAndParams), nil, nil, True,
        CREATE_DEFAULT_ERROR_MODE
        or NORMAL_PRIORITY_CLASS, nil, nil, StartupInfo, ProcessInformation);
    while True do
    begin
        GetExitCodeProcess(ProcessInformation.hProcess, lpExitCode);
        if lpExitCode <> STILL_ACTIVE then
            Break;
        Application.ProcessMessages;
    end;
    Result := Integer(lpExitCode);
end;
```

**Comment by cnpack** [comment]
Please refer to the "CnPack"->"Script Wizard"->"Script Library".
It allows to set to run a script trigger by certain events, as listed in right tree.
 
But your problem is, Pascal code <> Pascal Script. 
Pascal script has many limitations. your function maybe can't run.

**Comment by dshumko** [comment]
I know about library. The hard part was running the file.
Wrote simple console application and use RunFile for run it.
procedure RunFile(const FName: string; Handle: THandle = 0;  const Param: string = '');

**Comment by cnpack** [comment]
In fact, we already register a function named "WinExecAndWait32" to do this job.
You can directly call this function.

function WinExecAndWait32(const FileName: string; Visibility: Integer; ProcessMsg: Boolean): Integer;

Visibility is SW_NORMAL, etc
