### ISSUE TITLE
Input Helper not works in Delphi Type Section since CnWizard 1.2.5.1109

### ISSUE THREAD

**Issue by j1porandom** [cnpack/cnwizards#186]
Hi, 
since CnWizard 1.2.5.1109 until 1.2.8.1150, code input helper not works again in Delphi type section, using keyboard shortcut to popup manually not works too.
![Screenshot 2023-11-04 095007](https://github.com/cnpack/cnwizards/assets/148837263/b3f61252-9d0a-45c1-9b40-b6fcd5d7f146)

1.2.4.1095 works fine in Delphi type section.
![Screenshot 2023-11-04 095113](https://github.com/cnpack/cnwizards/assets/148837263/9f9ff48a-869e-4e72-b010-dea33c0e2cf9)

Thank You

**Comment by cnpack** [comment]
In 2nd pic, the popup is not correct for a new defined type name, so we hide it as a bug fixed since 1.2.5.

If you type THa = TC(cursor is here), we'll popup to show possible type names.

**Comment by j1porandom** [comment]
> In 2nd pic, the popup is not correct for a new defined type name, so we hide it as a bug fixed since 1.2.5.
> 
> If you type THa = TC(cursor is here), we'll popup to show possible type names.

Thank you for the explanation
typed "=TH" popup work, I'll delete manually "="
