### ISSUE TITLE
Code Input Helper Template PopUp Bug

### ISSUE THREAD

**Issue by j1porandom** [cnpack/cnwizards#187]
Found this issue after use CnWizard 1.2.8 , in 1.2.4 never had this issue.

1. When the above if condition uses begin...end bracket, the template popup works fine.
2. When the above if condition doesn't use begin...end brackets because only one statement, the template popup doesn't work.
![image](https://github.com/cnpack/cnwizards/assets/148837263/c8260b83-422e-40af-9107-530afca5b7a7)

Thank you

**Comment by cnpack** [comment]
Can't reproduce that. What's your Delphi version?

I see I can always pop templates such as "ifeb" whether the above if has begin or end.

If your problem always exists, could you provide the simplest source to reproduce it ?

**Comment by j1porandom** [comment]
> Can't reproduce that. What's your Delphi version?
> 
> I see I can always pop templates such as "ifeb" whether the above if has begin or end.
> 
> If your problem always exists, could you provide the simplest source to reproduce it ?

I using Delphi XE 10.2
![image](https://github.com/cnpack/cnwizards/assets/148837263/92425371-0506-4dac-af44-167e73812e11)

I attached the source code to reproduce the bug. It occurred below the third "if" statement, as seen in the screenshot above.
[New folder.zip](https://github.com/cnpack/cnwizards/files/13330460/New.folder.zip)

**Comment by j1porandom** [comment]
> See. It's a bug when we analysis the position information at cursor in the code piece you mentioned.
> 
> It's not easy to fix, and we now make a workaround for it. You can download our 1154 nightly-build and verify it.
> 
> https://www.cnpack.org/downbuilds.php

Installed nightly build 1154, the CodeInputHelper template popup is still not working below the third if statement.

**Comment by cnpack** [comment]
Oh. 1155 comes up for testing again. https://www.cnpack.org/downbuilds.php

**Comment by j1porandom** [comment]
> Oh. 1155 comes up for testing again. https://www.cnpack.org/downbuilds.php

Hi, thank you for the quick fix.
I can confirm that templates from Tool Windows > Template work, such as "if," "ifb," "ife," and "ifeb."
However, templates from CnPack > Input Helper > User Defined Symbol & Code Template still do not appear in the popup list.


![image](https://github.com/cnpack/cnwizards/assets/148837263/b52bd97f-c483-411d-ace0-dbdf311bc36b)

**Comment by cnpack** [comment]
Thank you for your detailed testing, we'll add them again in next nightly-build version.

**Comment by j1porandom** [comment]
I found another minor bug in input helper popup when using quoted string **with key code (#39)** instead QuotedStr function


`ADOQuery2.SQL[1]:='and var1='+QuotedStr(**ADOQuery1**.FieldByName('Field1').AsString);`
popup works fine with QuotedStr function

`ADOQuery2.SQL[1]:='and var1='#39+**ADOQuery1**.**FieldByName**('Field1').**AsString**+#39;`
input helper popup not working when using #39

Thank you

**Comment by cnpack** [comment]
What means "does not work"? No popup, or popup content empty?
Where's the cursor when the problem occurs in your code?

**Comment by j1porandom** [comment]
> What means "does not work"? No popup, or popup content empty? Where's the cursor when the problem occurs in your code?

Sorry for the confusion; you can ignore this problem, my mistake.

I discovered that `#39` works but I must add space after `#39+ `  like `#39+ ADO` for the popup to work fine. 
However, when I don't add a space like like `#39+ADO` , the popup does not appear. Additionally, when I manually trigger the popup (Alt+2), the list does not show ADOQuery1.

**Comment by cnpack** [comment]
Thank you for your report. It's a new bug for us to check whether can popup when meeting no Space.

Now 1156 fixed, please try it?

**Comment by j1porandom** [comment]
> Thank you for your report. It's a new bug for us to check whether can popup when meeting no Space.
> 
> Now 1156 fixed, please try it?

All the bugs that I mentioned above are now fixed. 
Thank you very much for the quick response and fix.

**Comment by cnpack** [comment]
OK. Also thank your for your detailed verification.
If new problem found, welcome to create new issue.

**Comment by cnpack** [comment]
OK. Also thank your for your detailed verification.
If new problem found, welcome to create new issue.

**Comment by j1porandom** [comment]
Hi, I apologize for reporting another popup bug (source code attached) [New folder.zip](https://github.com/cnpack/cnwizards/files/13411993/New.folder.zip)

![image](https://github.com/cnpack/cnwizards/assets/148837263/956deb33-30e4-4c73-8496-190a96391398)
`if ADOQuery1.FieldByName('myField').AsString='Y'  the`
The word "then" is not appearing in the popup.

Thank you

**Comment by cnpack** [comment]
Oh, Do NOT need apologize. Welcome to report bugs for us.

I make some fix about the "then" popup problem, please help to verify it when next nightly-build version published.

**Comment by cnpack** [comment]
Please try our 1157? 
https://www.cnpack.org/downbuilds.php

**Comment by cnpack** [comment]
Made some Optimize in 1158. If can, help to test it again? Thanks.

**Comment by j1porandom** [comment]
> Made some Optimize in 1158. If can, help to test it again? Thanks.

trying it now, 1157 works fine for me atm.
