### ISSUE TITLE
建议ASCII字符表工具稍作优化

### ISSUE THREAD

**Issue by winddriver** [cnpack/cnwizards#188]
可参考GExperts的ASCII Chart，如图
![image](https://github.com/cnpack/cnwizards/assets/3221597/bdca538b-895b-4ee4-ba3f-cd2d0b996cde)

这样设计可以方便的通过已知ASCII码反查对应的字符是哪个，同时也很方便查看已知字符的ASCII码

**Comment by cnpack** [comment]
我们的字符表，只要把鼠标指向哪个字符，其ASCII码的十进制与十六进制值就会出现在下面的状态栏上。

**Comment by winddriver** [comment]
可能你没太理解我要表达的意思，你们目前这个设计用于查询字符的ASCII码是没问题
但是还有另一种使用场景：就是我知道一个ASCII码，我想反查它代表的是哪个字符，你们目前这个工具就不是太方便了。
在做一些比较底层的开发调试的时候经常会面对一堆16进制的裸数据，有时候需要快速的对它进行字符解码，有这样一个码表工具就会很方便。

**Comment by cnpack** [comment]
左边与上边分别是ASCII码的高位和低位，像查数学用表那样，也能顺利找到某数字代表的位置吧。

如果把每个码都标上，那不就和GE一样了，那不如直接用GE。
