### ISSUE TITLE
 Reporting Issue with Delphi Unit Naming in Function format

### ISSUE THREAD

**Issue by marcosnielsen** [cnpack/cnwizards#189]
Dear CnPack Team,

I hope this message finds you well. I wanted to bring to your attention an issue I encountered while using the CNPACK Format function in Delphi when the unitname  contains the  word "local", such as "local.pas." or "local.entity.pas"

When attempting to use format with the unit name "local.pas," it concatenates the reserved word "unit" with "local," resulting in "unitlocal" instead of "unit local."

Is there any workaround or fix available for this issue? It seems to affect the functionality of the format function when dealing with unit names that include periods.

Thank you for your attention to this matter. I appreciate any guidance or resolution you can provide.

Best Regards,
Marcos Nielsen.

**Comment by marcosnielsen** [comment]
how to reproduce issue
[https://youtu.be/3tBM_0j5m1c](url)

**Comment by marcosnielsen** [comment]
[See Issue](https://youtu.be/3tBM_0j5m1c)

**Comment by cnpack** [comment]
Please try our 1160 nightly-build version?

https://www.cnpack.org/downbuilds.php

**Comment by marcosnielsen** [comment]
Hello,
It's working!
CnWizards_1.2.8.1160_Unstable.exe | 12/12/2023 14:28

A big thank you!
