### ISSUE TITLE
[Formatter] Can't format valid file

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#19]
https://github.com/remobjects/pascalscript/blob/master/Source/uPSCompiler.pas
```pascal
btPChar: VCType := FindAndAddType(Owner, '!OPENARRAYOFPCHAR', {$IFDEF PS_PANSICHAR}'array of PAnsiChar'{$ELSE}'array of PChar'{$ENDIF});
```

**Comment by shanzhashu** [comment]
Now for technical limitation, we Treat Compiler Directives as Comments. So if You have Code such as {$IFDEF XXX} var A: Byte; {$ELSE} Word;{$ENDIF}, Code Formatter will Raise Error.
