### ISSUE TITLE
Access violation at address 21D1EAD2 in module 'delphicoreide270.bpl'. Read of address 00000000

### ISSUE THREAD

**Issue by Makhaon** [cnpack/cnwizards#190]
[StackTrace.txt](https://github.com/cnpack/cnwizards/files/13691961/StackTrace.txt)
Ide crashes when I try to create new CnMemProof project.
Step to reproduce:
File > New > Other
CnPack > CnMemProof project
I've attach callstack file
I'm use Ver: 1.2.8.1150 Build 2023.11.01
Embarcadero® RAD Studio 10.4 Version 27.0.40680.4203 
Windows 10

**Comment by cnpack** [comment]
See. But can't fix now for we don't how to do it in High Version Delphi...   ;-(

**Comment by cnpack** [comment]
Make some fix, please try our latest nightly-build 1161?

https://www.cnpack.org/downbuilds.php

**Comment by Makhaon** [comment]
Seems that issue was fixed. Thank you very much!
