### ISSUE TITLE
TCnMethodHook overwrites other IDE method hooks and breaks other IDE wizards

### ISSUE THREAD

**Issue by vintagedave** [cnpack/cnwizards#2]
`TCnMethodHook` need to be unhooked and re-hooked every time the original method is called, with code like so:

    MyCnHook.UnhookMethod;
    try
      OriginalMethod(1, 2, 3);
    finally
      MyCnHook.HookMethod;
    end;

The call to `HookMethod` overwrites any existing hooks that are already in place - such as those from other IDE wizards.  This means that CnPack can't be installed at the same time as any other wizard that needs to hook the same methods.

In addition, `TCnMethodHook` is slow - it needs to change virtual memory protection, write the memory, update protection, and flush the CPU instruction case every time a hooked method is called. For methods where performance is important, such as IDE painting, this is not ideal.

If CnPack's method hook code was updated to use DDetours (an open-source, MPL-licensed, method hook library for Delphi - see https://code.google.com/p/delphi-detours-library/wiki/DDetours ) it would solve these problems.

DDetours hooks once - it does not need to hook and unhook every time. Instead, the original method implementation is called via new "trampoline" pointer. Several DDetours hooks can be installed on the one method, and will "chain" - that is, the first's trampoline is the second, and its trampoline is the third, and so forth. Finally, because it only patches once, it is faster and does not flush the CPU cache or write to memory every time it is used.

I have modified a fork of CnPack to use DDetours, and verified that (a) it works, and (b) several IDE wizards can now hook the same functions at the same time.  I will submit a pull request soon after entering this issue.

**Comment by shanzhashu** [comment]
Closed. Only use DDetours in High version of IDE.

**Comment by shanzhashu** [comment]
Closed. Only use DDetours in High version of IDE.

**Comment by shanzhashu** [comment]
Closed. Only use DDetours in High version of IDE.

**Comment by piker00** [comment]
![2](https://cloud.githubusercontent.com/assets/11677236/20218946/04f1690a-a838-11e6-9372-e42148d86ac9.gif)
