### ISSUE TITLE
0.3 is not valid floating point value

### ISSUE THREAD

**Issue by vectoris** [cnpack/cnwizards#201]
I get this error every time I run IDE with  last unstable build.
<img width="479" alt="Screenshot 2024-06-30 072648" src="https://github.com/cnpack/cnwizards/assets/14171882/ece09b27-3b1f-4545-bc8e-8967f293edb6">

**Comment by cnpack** [comment]
We'll check this immediately.

**Comment by vectoris** [comment]
there are no files with the *.json extension in this folder.
I checked the contents of other files, they do not contain such a value.

I think that the file is simply not created due to this error.

According to the fact that in the local environment, can be configured to use comma or a period for separate a decimal number
I recommend using something like this:

function MyStrToFloat(const S: string): Extended;
const
  Komma: TFormatSettings = (DecimalSeparator: ',');
  Dot: TFormatSettings = (DecimalSeparator: '.');
begin
  if not TryStrToFloat(S, Result, Komma) then
    Result := StrToFloat(S, Dot);
end;

**Comment by cnpack** [comment]
Oh I see. Thanks for your solution.
We'll do some research to find how it can work on lower versions of Delphi which does not have FormatSettings.

**Comment by vectoris** [comment]
My delphi is 12.1
