### ISSUE TITLE
Component properties comparision window font height out of bounds

### ISSUE THREAD

**Issue by vectoris** [cnpack/cnwizards#203]
![Screenshot 2024-07-05 132755](https://github.com/cnpack/cnwizards/assets/14171882/b49be57f-06cb-441d-8ed7-3a4ebb05711d)

**Comment by cnpack** [comment]
We add font setting in 1195 nightly-build and this problem should be fixed.
Please try it? https://www.cnpack.org/downbuilds.php

**Comment by vectoris** [comment]
Good job! Thanks!
