### ISSUE TITLE
Bug  Does not save the width of open dialog grids. 

### ISSUE THREAD

**Issue by luapfr** [cnpack/cnwizards#204]
The two dialogs for opening forms and units are not saving the width size of the columns when I increase it, close it and open it, it does not take the last width I entered.

**Comment by cnpack** [comment]
Please tell us the version of Delphi and CnWizards?

**Comment by luapfr** [comment]
Any versions 

CnWizards_1.3.1.1198_Unstable
CnWizards 1.3.1.1181 Released

Embarcadero® RAD Studio 12 Version 29.0.51961.7529 



https://github.com/user-attachments/assets/0e0442d1-ede8-45de-9624-2bd4c3bb4039

**Comment by cnpack** [comment]
Oh, seems we can't get the listview column width change message in D12.
We make some fix in 1199, please try it?

**Comment by luapfr** [comment]
Problem solved, thank you very much.
What do you tell me that creating a way to save other Delphi forms like GExpert does ?

https://github.com/cnpack/cnwizards/issues/198
