### ISSUE TITLE
cnPack won't load into D12.2 patch 1.

### ISSUE THREAD

**Issue by ijbranch** [cnpack/cnwizards#212]
Just installed D12.2 patch 1.
cnPack will not load into delphi.
![image](https://github.com/user-attachments/assets/3f135e4f-ae05-48ba-834e-9bcf7e154141)

**Comment by teslasystemsx** [comment]
I have installed CnPack to patched RAD Studio and there are no any problems.
<img width="516" alt="About" src="https://github.com/user-attachments/assets/ab79be30-1b8d-44b2-a6aa-502357c2a5ac">

**Comment by ijbranch** [comment]
Ditto.

**Comment by cnpack** [comment]
Please try our latest nightly-build version 1214?
https://www.cnpack.org/downbuilds.php?lang=en

12.2 Patch 1 are not compatible with 12.2 for many IDE Runtime packages. We need recompile it under 12.2 Patch 1.

**Comment by cnpack** [comment]
> I have installed CnPack to patched RAD Studio and there are no any problems. <img alt="About" width="516" src="https://private-user-images.githubusercontent.com/140281857/378236711-ab79be30-1b8d-44b2-a6aa-502357c2a5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTMxNjksIm5iZiI6MTcyOTY1Mjg2OSwicGF0aCI6Ii8xNDAyODE4NTcvMzc4MjM2NzExLWFiNzliZTMwLTFiOGQtNDRiMi1hNmFhLTUwMjM1N2MyYTVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMzA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDM4ZTQ3YTYzYTRlYjNhNjE2MmE0MjE3MDBhZmE2NjZmZmEzNDkxYzRhNmM5ZTljNWQ1ZGZmOWU4YmZjYTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TT55L5UceeHlp4fHIE_5sMxRZvxKrqfmeUdvHywpj68">

Your patch 1 are different with others, for we know the patch 1 version is 29.0.53982.0329, which need CnWizards to be recompiled.

**Comment by teslasystemsx** [comment]
> > I have installed CnPack to patched RAD Studio and there are no any problems. <img alt="About" width="516" src="https://private-user-images.githubusercontent.com/140281857/378236711-ab79be30-1b8d-44b2-a6aa-502357c2a5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTMxNjksIm5iZiI6MTcyOTY1Mjg2OSwicGF0aCI6Ii8xNDAyODE4NTcvMzc4MjM2NzExLWFiNzliZTMwLTFiOGQtNDRiMi1hNmFhLTUwMjM1N2MyYTVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QwMzA3NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDM4ZTQ3YTYzYTRlYjNhNjE2MmE0MjE3MDBhZmE2NjZmZmEzNDkxYzRhNmM5ZTljNWQ1ZGZmOWU4YmZjYTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TT55L5UceeHlp4fHIE_5sMxRZvxKrqfmeUdvHywpj68">
> 
> Your patch 1 are different with others, for we know the patch 1 version is 29.0.53982.0329, which need CnWizards to be recompiled.

It differs, because it was installed using GetIt, it's not a clean installation. But, as I said, everything works good for me, no any problems.

**Comment by cnpack** [comment]
OK. We using the version number to determine which DLL will be loaded. It should be OK for clean installation or GetIt upgrade.
