### ISSUE TITLE
Ai Coder - Claude Error  0 max_tokens: 10240 > 4096

### ISSUE THREAD

**Issue by Corriscant** [cnpack/cnwizards#214]
Using  Claude 3.5 Sonnet and Haiku - same error

0 max_tokens: 10240 > 4096, which is the maximum allowed number of output tokens for claude-3-sonnet-20240229

0 max_tokens: 10240 > 4096, which is the maximum allowed number of output tokens for claude-3-haiku-20240307

![изображение](https://github.com/user-attachments/assets/d7522b2b-8f65-468f-b039-5d83e13bdfbd)

**Comment by cnpack** [comment]
Oh, Max Token Parameter now is not for an Option. we'll change its default value to 4096.

**Comment by cnpack** [comment]
A temporary solution: Close Delphi. change My Documents\CnWizards\AICoderConfigClaude.json
Change MaxToken from 10240 to 4096

**Comment by Corriscant** [comment]
I tried your solution.
Didn't work.

![изображение](https://github.com/user-attachments/assets/a6259586-dbb9-4331-b1a0-e7dc47670033)

And now limit is 8192.
But looks like Ai Coder don't care what is written in Jason "MaxTokens"

I close Delphi. Change Json. 
Open Delphi  (checking Jason still have 8192). 
Open Ai Coder Chat window.  Test - recieve Error (on screenshot).
Close Delphi.  
Open Jason - thare is 10240 again.

Looks like Ai Coder override Json with his own default value.

**Comment by cnpack** [comment]
We'll do some debugging to slove this problem in next version.

**Comment by cnpack** [comment]
We make the MaxTokens parameter configuable in 1220 nightly-build version and set default value to 4096.

Please try to download and verify it ?
https://www.cnpack.org/downbuilds.php?lang=en

**Comment by Corriscant** [comment]
Yes. It's work now. Thank you.
