### ISSUE TITLE
New Feature block 

### ISSUE THREAD

**Issue by marcosnielsen** [cnpack/cnwizards#217]
Hi,

First of all, I want to say that the CNPack formatter is superior to others.
Congratulations to the creators of this excellent functionality!

I’d like to ask if it’s possible to add an option to format code with indentation when using parentheses ().

For example, here’s how I’d like my code to be formatted:
![image](https://github.com/user-attachments/assets/b1afc45c-c7b0-4b25-90aa-791dc888730a)

Currently, this is how the code is formatted:
![image](https://github.com/user-attachments/assets/b2e17a40-b265-4339-8611-b2ab7040567a)

Would it be possible to implement such an option?

Thank you!

**Comment by marlonnardi** [comment]
+1

**Comment by softniels-samuel-parastchuk** [comment]
+1

**Comment by cnpack** [comment]
In fact, we think it's a bug in our formatter. We should make indent for these parameters in function calling.

Could you paste some sample code here for our debugging?

**Comment by marcosnielsen** [comment]
hi, here a mini - sample
![image](https://github.com/user-attachments/assets/f4c7e67c-721b-4c84-98cf-1652d0a16fe8)

[sample.7z.txt](https://github.com/user-attachments/files/17982133/sample.7z.txt)
to try rename sample.7z.txt to sample.7z

**Comment by marcosnielsen** [comment]
or try it
```program Project1;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Unit1 in 'Unit1.pas';

begin
  try
    var ValueA := 100;
    var ValueB := 100;
    // Before applying the code formatter to the TMyCalc class
    TMyCalc
      .New(Now)    // <-- No breakline here
      .WriteSum(   // <-- Breakline here
        ValueA,
        ValueB
      ); //
    // After applying the code formatter to the TMyCalc class
    TMyCalc
      .New(Now)
      .WriteSum(
      ValueA,
      ValueB
      );
  except
    on E: Exception do
      Writeln('Error: ', E.Message);
  end;
  Readln;
end.
```

**Comment by cnpack** [comment]
Get it.

We make some fix and bulid a new nightly-bulid 1222 at  https://www.cnpack.org/downbuilds.php
Please try it?
