### ISSUE TITLE
cnConst is lost

### ISSUE THREAD

**Issue by mvbressler** [cnpack/cnwizards#28]
Hi When I try to compile cnWizard_D10.dpk, it show me the message error: Unit 'CnConsts' not found.

**Comment by cnpack** [comment]
You need also clone the repository https://github.com/cnpack/cnvcl.git at the same level with cnwizards.git

**Comment by mvbressler** [comment]
Thanks a lot. It works perfectly. Great work!!!

2016-01-12 20:46 GMT-05:00 CnPack Team <notifications@github.com>:
