### ISSUE TITLE
Formatter ReadOnly keyword

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#29]
pls can you add readonly keyword to ignore list couse its used in almost every vlc component and every time i format unit it will change     
```pascal
property ReadOnly: Boolean read GetReadOnly write SetReadOnly default False;
```

to

```pascal
property readonly: Boolean read GetReadOnly write SetReadOnly default False;
```

**Comment by cnpack** [comment]
OK. We'll make readonly be the keyword only after property. Now 813 nightly-build integrated this fix.

http://www.cnpack.org/downbuilds.php

**Comment by Sorien** [comment]
thx
