### ISSUE TITLE
[Formatter] Do not lowercase "export" keyword

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#30]
```
Item.Export := 'foo'
```

after formatting

```
Item.export := 'foo';
```

~~it's not even reserved keyword in delphi ~~
~~http://docwiki.embarcadero.com/RADStudio/Seattle/en/Fundamental_Syntactic_Elements#Reserved_Words~~

**Comment by shanzhashu** [comment]
Fixed in latest code.
