### ISSUE TITLE
UAC和CnDebugViewer

### ISSUE THREAD

**Issue by uian2000** [cnpack/cnwizards#33]
在UAC（我这里是Win10环境）下，CnDebugViewer和被调试程序必须都运行在管理员权限下，DebugViewer才能接收到调试信息。
这个问题有可能解决吗？
在后UAC环境下的ChangeWindowMessageFilter是否有助于解决这个问题？

**Comment by shanzhashu** [comment]
CnDebugViewer最新版本的选项中有个开关，可以使用本地模式。这种情况下不需要管理员权限。

当然，相关的CnDebug.pas也需要改动，需要把头部的

// {$DEFINE LOCAL_SESSION}

给取消注释。
