### ISSUE TITLE
[Formatter] bugs

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#34]
1. cannot format unit when function name prefixed with &

```
https://github.com/gabr42/GpSQLBuilder/blob/master/GpSQLBuilder.pas
```

2. formatter adds blank lines after each call
```
https://github.com/gabr42/GpSQLBuilder/blob/master/GpSQLBuilder.AST.pas
```

CnPack 1.1.0.826_Unstable

**Comment by shanzhashu** [comment]
1. The latest nightly-build 843 fix this & problem, please try it again?
2. I can't see the blank lines, could you try 843, too?

**Comment by Sorien** [comment]
yes it adds blank lines before `unit GpSQLBuilder.AST;`

```pascal
///     1.0: 2015-04-29
///       - Released.
///</para></remarks>

unit GpSQLBuilder.AST;
```

after five code formatings
```pascal
///     1.0: 2015-04-29
///       - Released.
///</para></remarks>






unit GpSQLBuilder.AST;

{$IFDEF FPC}
  {$MODE DELPHI}
{$ENDIF}
```

**Comment by Sorien** [comment]
btw it would be nice to have configurable maximum allowed blank lines

**Comment by shanzhashu** [comment]
Seems the blank lines are caused by the #$A Line break, not #$D$A in this file.
Maybe we have troubles to treat simple #$A as the line break signs.

**Comment by Sorien** [comment]
it's already fixed
