### ISSUE TITLE
[Feature] auto wrap uses list at xx / or wrap at right margin

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#37]
few versions back uses list was wrapped according "right margin" now when i have "Auto wrap line at" disabled it's producing long lines

**Comment by shanzhashu** [comment]
Not understand exactly, could you provide snapshot(s) for format result and the setting dialog of Code Formatter?

**Comment by Sorien** [comment]
before 

```
uses
  SysUtils, Windows, ZConnection, DB, ZAbstractConnection, ZDbcIntfs, ZDataset, Generics.Collections, DPGrids,
  ZAbstractDataset, Classes, Version, Variants, SyncObjs, ThreadHelper, ZDbcInterbase6, ZSqlProcessor;
```

after 849
```
uses
  SysUtils, Windows, ZConnection, DB, ZAbstractConnection, ZDbcIntfs, ZDataset, Generics.Collections, DPGrids, ZAbstractDataset, Classes, Version, Variants, SyncObjs, ThreadHelper, ZDbcInterbase6, ZSqlProcessor;
``` 

![image](https://cloud.githubusercontent.com/assets/1270275/17845269/ed6e7d68-6840-11e6-8559-d785bdadd20d.png)

**Comment by shanzhashu** [comment]
Oh, a new bug for Line Wrap Width feature.

Now I use a separate Line Wrap Width Param for uses clause internally. and 852 nightly-build version integrated this fix. Please try to download it and verify it?

**Comment by Sorien** [comment]
yes, its fixed in 852, thx
