### ISSUE TITLE
Source Highlighter misplaced

### ISSUE THREAD

**Issue by monky2k6** [cnpack/cnwizards#38]
After v1.1.1.849 the SourceHighlighting in Delphi 2007 is misplaced. After 50 characters or so, if you set the cursor on a expression (example: TControl) it highlights all occurences, but the first highlight gets displayed 9 characters to the right, overlapping other code.

**Comment by shanzhashu** [comment]
Could you provide the misplaced file to us for debugging? master@cnpack.org

You can just remove the private part if has, and send misplaced part to us.

And, could you tell me whether the "use tab character" option is checked or not in your Delphi Source Options?

**Comment by fernando-takeshi** [comment]
@shanzhashu Hello, is there any updates on this? I'm having the same problem (Delphi 2007), which I believe started on a version prior to 1.1.1.849 Build 2016.08.15, though I'm not exactly sure. I can also provide some more information, if necessary. Here are some screenshots. Cheers!

![tab_character](https://cloud.githubusercontent.com/assets/6924668/19367248/b39c3356-9170-11e6-8445-17a98558351b.png)
![example](https://cloud.githubusercontent.com/assets/6924668/19367249/b39e8048-9170-11e6-9551-3c1e6b221375.png)
![example_highlighted](https://cloud.githubusercontent.com/assets/6924668/19367250/b3a3f8c0-9170-11e6-84f7-2ac4a3816559.png)

**Comment by shanzhashu** [comment]
Thanks. I see the options. It helps much.
But could you send me the file mis-displayed to me ? I'd like to check whether there are truly Tab chars in it and make our position calculation messed up.

**Comment by fernando-takeshi** [comment]
I sent it via email, to master@cnpack.org. Cheers!
