### ISSUE TITLE
[Code Formatter]blank lines after `end.`

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#39]
code formatter inserts blank line(s) after `end.`

Version: 1.1.1.854_Unstable Build 2016.09.05

```pascal
function TForm.Foo(): Boolean;
begin
end;

end.
```

after formatting
```pascal
function TForm.Foo(): Boolean;
begin
end;

end.


```

**Comment by shanzhashu** [comment]
It comes to fix an 'ending' problem when select 'end.' at the end of a Pascal file in IDE.

**Comment by shanzhashu** [comment]
Now playing a tricky hand to avoid duplicated CRLFs.
