### ISSUE TITLE
Code divider wrong possitioning

### ISSUE THREAD

**Issue by piker00** [cnpack/cnwizards#45]
![codedelbug](https://cloud.githubusercontent.com/assets/11677236/21372795/8c3897e2-c72a-11e6-8efb-9c00ab43d260.png)

**Comment by shanzhashu** [comment]
Could you download our latest nightly-build version 877 to try it again? This feature was in refactoring before so maybe has some side effects.

http://www.cnpack.org/downbuilds.php
