### ISSUE TITLE
[Code Formatter] Format Error Symbol Expected

### ISSUE THREAD

**Issue by TheOne320** [cnpack/cnwizards#48]
```delphi
begin
  someBoolean    := false;
  input[0]  := true;
  input[65] := false;

  for counter := 1 to 64 do
  begin
    input[counter] := false;
  end;

  for counter := 1 to 64 do
  begin
    output[counter] := false;
  end;

  input[0] := true;
end.
```

When trying to format this code I get an error.

**Comment by TheOne320** [comment]
I also found that using the procedure `procedure Str(X [: Width [: Decimals ]]; var S)` with for example Str(L:f,s); gives an error when using the code formatter.

**Comment by shanzhashu** [comment]
About the first problem, now I can't reproduce it in latest code. Could you download our latest nightly-build version to try it again?

http://www.cnpack.org/downbuilds.php?lang=en

**Comment by shanzhashu** [comment]
Now latest nightly-build 877 version supports Str(X [: Width [: Decimals ]]; var S) but maybe has some side effects. Could you help to try it?

**Comment by TheOne320** [comment]
I am back at work tomorrow and will try it.

**Comment by TheOne320** [comment]
So, the Str(X...) does not give an error but the first code snippet still causes an error. (Daily 878)
![error](https://cloud.githubusercontent.com/assets/7705568/22829475/16cf10ac-efa3-11e6-9f17-f4417895d146.PNG)

**Comment by shanzhashu** [comment]
Oh,our formatter can only process full file starting with program/library/unit keyword, not just a code snippet start with begin or other keywords.
