### ISSUE TITLE
Firemonkey form designer error

### ISSUE THREAD

**Issue by thachngopl** [cnpack/cnwizards#49]
Hi,

Drag & drop and component into FMX form designer, It will paint a red rectangle.

**Comment by shanzhashu** [comment]
Thanks for your report. Could you provide a snapshot?

**Comment by thachngopl** [comment]
Here you are:
![capture](https://cloud.githubusercontent.com/assets/16706272/23103523/dbe1f0f6-f6ee-11e6-8863-3639fa230225.PNG)

RAD 10.1 Update 2
Windows 7, Classic theme.
Cnpack: http://www.cnpack.org/download/unstable/CnWizards_1.1.2.880_Unstable.exe

**Comment by thachngopl** [comment]
Turn off "Tab Order Wizard", the IDE become OK!

**Comment by shanzhashu** [comment]
Thanks for your investigation. I still can't reproduce this problem but I'll check it in Tab Order Wizard.

**Comment by thachngopl** [comment]
I changed font name for Tab Order Wizard from "MS Sans Serif" to "Tahoma", the IDE became OK!
If I chose "MS Sans Serif", the Canvas.TextWidth, Canvas.TextHeight went wrong (line 181, CnFmxTabOrderUtils.pas).

**Comment by shanzhashu** [comment]
I also reproduce once for this case, FMX's Canvas.TextWidth and Canvas.TextHeight return 2 huge values! So the big rectangle appears.

But now it becomes OK again. ;-(

I'll do some limitation for these 2 values, and will change the default font name from "MS Sans Serif" to "Tahoma".

**Comment by thachngopl** [comment]
FMX only supports True Type Font. That's why the IDE becomes wrong when I select MS Sans Serif 😄

**Comment by shanzhashu** [comment]
Now we also change the default fonts to "Tahoma." Closed.
