### ISSUE TITLE
smart paste does not work as expected

### ISSUE THREAD

**Issue by rschroedter** [cnpack/cnwizards#59]
The smart paste feature does not work as expected anymore. 
I expect the replacement of the text under the cursor by pressing [STRG]+[V]. As of nightly built 1.1.3.903.
In the newer Version, the text under the cursor is not replaced but inserted at cursor position ;-(.

**Comment by shanzhashu** [comment]
We improved this feature for auto-aligning. You can download our latest 907 nightly-build version and check the new option in "Editor Enhancement Settings" dialog to enable this "text-under-cursor-replaced" function.

http://www.cnpack.org/downbuilds.php

**Comment by rschroedter** [comment]
The improvement works well and the text under the cursor is replaced again.

Thxs for the immediate fix. Issue may be closed.
