### ISSUE TITLE
Formater error - blank char in class declaration 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#60]
```pascal
type
  TFoo = class(TForm) 
    QuickReport: TQuickRep;
end;
```
![image](https://user-images.githubusercontent.com/1270275/29121659-bcc94a0a-7d0f-11e7-921c-ee0626ca4103.png)

**Comment by shanzhashu** [comment]
Can't reproduce this problem. Could you tell me the Version of Delphi and CnWizards?

**Comment by Sorien** [comment]
sorry my bad, it seems to be some weird char, i thought that its space but i can't even copy it 
ver: 1.1.3.906_Unstable Build 2017.07.31

**Comment by Sorien** [comment]
when i open it in sublime it looks like 
![image](https://user-images.githubusercontent.com/1270275/29124003-d9cbd034-7d17-11e7-9abd-e0e18afafbf1.png) 

don't know how it gets there :D

**Comment by shanzhashu** [comment]
OK.
