### ISSUE TITLE
Problem with background highlight current identifier at cursor

### ISSUE THREAD

**Issue by jaclas** [cnpack/cnwizards#62]
Delphi Tokyo, last nightly cnpack:

this is ok:
![vps_2017 10 19_01](https://user-images.githubusercontent.com/17312717/31773576-79ce5bf8-b4e3-11e7-91e6-04881fff7463.png)

this is bad:
![vps_2017 10 19_02](https://user-images.githubusercontent.com/17312717/31773592-832b03f4-b4e3-11e7-8053-f438b890902d.png)

**Comment by shanzhashu** [comment]
implements is a keyword so we do not highlight it.

**Comment by jaclas** [comment]
sad that it is impossible :-(
please close issue
