### ISSUE TITLE
CnWizards crashes on Delphi startup

### ISSUE THREAD

**Issue by stepand76** [cnpack/cnwizards#63]
CnWizards crashes every time I start Delphi. After I confirm the Windows crash dialog Delphi continues to start and works as usual but I missing CnWizards... If I uninstall CnWizards then Delphi starts without any issue. If I install CnWizards again, problem is back.

See the attached pictures,
Windows 10 (1709), x64, Delphi XE5, CnWizards 1.1.3.896.

If you need an additional info to identify the issue then please do no hesitate to ask.

![clipbrd1](https://user-images.githubusercontent.com/8308820/32419432-08b8401a-c27a-11e7-9d95-74d7eb1dc75a.png)
![clipbrd2](https://user-images.githubusercontent.com/8308820/32419430-089be848-c27a-11e7-9476-b27199f59977.png)
![clipbrd3](https://user-images.githubusercontent.com/8308820/32419428-087ac0e6-c27a-11e7-8c95-0544d8a20e0d.png)
![clipbrd4](https://user-images.githubusercontent.com/8308820/32419427-085b0c24-c27a-11e7-9ab4-80563082eccf.png)

**Comment by shanzhashu** [comment]
So wired the problem and thanks for your report. 
First, could you download our latest nightly-build 915 version to try whether it still exists or not?

http://www.cnpack.org/downbuilds.php

**Comment by stepand76** [comment]
It was because of Windows Insider Build. Once I went back to official Fall Creators Update it works fine. Sorry for confusing.
