### ISSUE TITLE
Replace unicode caractere

### ISSUE THREAD

**Issue by cirtasoft** [cnpack/cnwizards#64]
![image](https://user-images.githubusercontent.com/12158881/32864843-f4df81d6-ca60-11e7-962b-725832764bbd.png)

**Comment by shanzhashu** [comment]
Thanks for your report. Could you tell me which version of Delphi you use?
And which OS? which Language of OS?

**Comment by cirtasoft** [comment]
Delphi Seattle Fransh

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by shanzhashu** [comment]
Thanks. it's a Bug. Now I fix it. You can download our latest nightly-build version 916 and check it.

http://www.cnpack.org/downbuilds.php
