### ISSUE TITLE
" in VerInfo_Keys break compiling project in XE5

### ISSUE THREAD

**Issue by VladimirSrednikh** [cnpack/cnwizards#67]
DelphiXE5.
CnVerEnhancements turn on.

Make new project, set CompanyName inVersionInfo to "test"
Compile it
Got error with Projectname.vrc:
[BRCC32 Error] Projectname.vrc(50): undefined keyword or key name: CompanyName

> {
>  BLOCK "StringFileInfo"
>  {
>   BLOCK "040904E4"
>   {
>    VALUE ""CompanyName",  """""test""""""\000\000"
>    VALUE "FileVersion",  "1.0.0.0\000\000"
>    VALUE "ProductVersion",  "1.0.0.0\000\000"
>    VALUE "LastCompiledTime",  "2018.01.23 11:07:17\000\000"
>   }
>  }
>  BLOCK "VarFileInfo"
>  {
>   VALUE "Translation", 1033, 1252

Reason to this - using DelimitedText, which AnsiQuotedStr every line.

Solution:
Replace 

>     Sl.Delimiter := ';';
>     Sl.StrictDelimiter := True;
> {$IFDEF DEBUG}
>     CnDebugger.LogMsg('VerEnhance Set VerInfo_Keys: ' + Sl.DelimitedText);
> {$ENDIF}
> CnOtaSetProjectCurrentBuildConfigurationValue(FCurrentProject, csVerInfoKeys, Sl.DelimitedText);

to 

>     S := '';
>     for Idx := 0 to Sl.Count - 1 do
>     if S = '' then
>       S := SL[Idx]
>     else
>       S := S + ';' + SL[Idx];
> 
> {$IFDEF DEBUG}
>     CnDebugger.LogMsg('VerEnhance Set VerInfo_Keys: ' + S);
> {$ENDIF}
>     CnOtaSetProjectCurrentBuildConfigurationValue(FCurrentProject, csVerInfoKeys, S);

**Comment by shanzhashu** [comment]
Thanks for your report. It's a bug for parsing Quota, now we fixed this problem using your way. Code committed.
