### ISSUE TITLE
[1.1.4.921] Options Buttons diplay bug

### ISSUE THREAD

**Issue by TheOne320** [cnpack/cnwizards#68]
I installed version 1.1.4.921 on RAD Studio 10.2.2 and the cnpack options menu is only showing the top halves of the bottom buttons.  
![options](https://user-images.githubusercontent.com/7705568/35441785-22d7dfbc-02a5-11e8-9cc1-88301d18659c.PNG)

**Comment by shanzhashu** [comment]
Please try our 1.1.4.923? I do some size adjustment for Theme.

**Comment by TheOne320** [comment]
Yes, it is fixed.
