### ISSUE TITLE
IDE Main Form Enhancements wizard causes IDE toolbars to misalign

### ISSUE THREAD

**Issue by DelphiWorlds** [cnpack/cnwizards#70]
The TCnPaletteEnhanceWizard.AdjustMainMenuBar method causes the IDE toolbars to misalign. Please refer to the attached image.

![cnwizardsbug](https://user-images.githubusercontent.com/22670829/39951240-2d6d13a0-55c7-11e8-8295-d78b9313fd03.png)

Even if this wizard is disabled, the problem still occurs. I have had to download the source, comment out the routine, and recompile

**Comment by shanzhashu** [comment]
This routine is used to align the controls right to menubar, but I check the code, it's called every time even options disabled. Now I correct it and commit the fix. Could you pull it and recompile it to verify it again?
