### ISSUE TITLE
FMX Frames dont work with CNWizard

### ISSUE THREAD

**Issue by protoror** [cnpack/cnwizards#72]
After delete CNPack FMX Frames work fine

**Comment by baka0815** [comment]
Did you check your dproj file? Sometimes Delphi deletes the 'dfm' types in the project file and then frames don't work.

**Comment by protoror** [comment]
Delphi 10.2.3
https://imgur.com/a/DSawlWt
i try this on new FMX project, create Firemonkey Frame with button, and put Frames in mainform, dialog display not a correct - no name and text shifted and in toolbar i see frtest.dfm idk why dfm (no dfm files in project folder and in dproj file) and if i put frame i get error.
On forum me give advice delete CnPack, i delete and after this i get standart put frame dialog and frame past correct.

**Comment by shanzhashu** [comment]
Thanks for your description. After checking, it's a fmx name parsing problem. Now I fixed, could you try the latest 935 nightly-build version to try it?

http://www.cnpack.org/downbuilds.php

**Comment by protoror** [comment]
For in 935 fine
