### ISSUE TITLE
Procedure List - fuzzy matching issue

### ISSUE THREAD

**Issue by jaclas** [cnpack/cnwizards#75]
See screen:

![vps_2018 09 27_02](https://user-images.githubusercontent.com/17312717/46148237-e8536680-c267-11e8-94ed-27440773d445.png)

CnPack 1.1.5.941
Delphi Tokyo

**Comment by shanzhashu** [comment]
Thanks for your report. 

It's a bug when we parsing some methond name such as MethodName<TType1, TType2> with Generic declarations. Now I fixed.

The next nightly-buid version will integrate it.

**Comment by jaclas** [comment]
Maybe you should consider using DelphiAST for a comprehensive solution to parsing problems?

[https://github.com/RomanYankovsky/DelphiAST](url)

**Comment by jaclas** [comment]
![vps_2018 10 15_03](https://user-images.githubusercontent.com/17312717/46970589-d40dc700-d0b9-11e8-9875-4ddba8f0612f.png)

Thanks!
