### ISSUE TITLE
Procedure List - destructor C++ code

### ISSUE THREAD

**Issue by beri75** [cnpack/cnwizards#76]
Hi, 
C++ destructors are not reported properly on Procedure List, member function type should be "destructor" instead of "procedure" and related to class "XXX" in my example. Selection "XXX" in Procedure List brings to the disappear of the member function. 
A trash icon should be more appreciated lastly :)

![2018-10-31_174007](https://user-images.githubusercontent.com/28294768/47804569-6c9c7c00-dd35-11e8-8d2d-ab383bdbc356.png)

**Comment by shanzhashu** [comment]
Thanks for your report. It's a BUG when we meeting '~' Char in parsing C++ Code. Now fixed and committed.

**Comment by shanzhashu** [comment]
Please download our new nightly-build vesrion 1.1.5.948 to verify it?

http://www.cnpack.org/downbuilds.php?lang=en

**Comment by beri75** [comment]
Works fine now, thank you guys!
