### ISSUE TITLE
cnpack更新到1.1.5.946之后，函数过程无法使用

### ISSUE THREAD

**Issue by xingjohn** [cnpack/cnwizards#77]

**Comment by shanzhashu** [comment]
请问具体问题是什么？可否详细反馈一下？

另外，我们的最新每日构建版948修正了两个C/C++代码的函数过程列表问题，如果您看到描述和您碰到的问题一致，可以下载试用一下。
http://www.cnpack.org/downbuilds.php?lang=en

**Comment by xingjohn** [comment]
你好，非常感谢您的回答.
我的朋友说你们18年如一日的跟进，这种精神让我们感动。
感谢你们辛苦的付出。
我刚才使用了1.1.5.948构建版之后。再次使用函数过程，也就是快捷键ctrl+D 
假如输入Q，我希望的是匹配函数名称。如下图：
不好意思，图片多次上传失败.
我再描述下吧，在cpp文件界面，使用ctrl+d。假如输入q。而刚好类名也含有q
假如类名是TFormQxtlOrder，而类的函数名有一个叫Query
那么此时，query不会被匹配到(匹配函数过程名开头)
希望：只匹配函数过程名开头，而对类的作用域(TFormQxtlOrder::)不用匹配
或者至少要匹配到类名和函数名，所有被匹配到到的，可以被高亮显示。
这只是我在使用过程中发现的一点问题。希望被采纳。

**Comment by shanzhashu** [comment]
感谢您的鼓励以及详细的报告，可否告知一下当时您复现此问题时，工具栏上使用的匹配模式是什么？函数列表窗口的工具栏上有三个匹配按钮，分别是从头、中间、模糊，我们想知道是哪个匹配模式出了问题。

**Comment by shanzhashu** [comment]
![image](https://user-images.githubusercontent.com/3039960/48067716-e5a34400-e20b-11e8-9285-882f2135f555.png)
我看了“匹配开头”的模式下，query函数能够显示出来，不过高亮的字符却是类名中的Q，是否这是您所说的问题？这个绘制的偏差我们会马上修正。

**Comment by shanzhashu** [comment]
了解。 http://www.cnpack.org/downbuilds.php?lang=zh-cn 
949的每日构建版本针对您提到的问题做了修正，烦请下载试用？

**Comment by xingjohn** [comment]
您好！
谢谢您的帮助，我已经下载试用949版本，目前没发现其他问题。
![image](https://user-images.githubusercontent.com/28851128/48339217-a5781180-e6a2-11e8-9d8f-e73302ca471a.png)
