### ISSUE TITLE
Any way to use CnWizard on Delphi 10.3

### ISSUE THREAD

**Issue by soonsam123** [cnpack/cnwizards#79]
Is there any way to use the latest version of CnWizard 1.1.5.946 on the latest Delphi version 10.3 Rio?

**Comment by shanzhashu** [comment]
Please refer to our latest nightly-build version: 

http://www.cnpack.org/downbuilds.php?lang=en

Still in testing.

**Comment by shanzhashu** [comment]
I also add a README.md to indicate it.

**Comment by soonsam123** [comment]
You guys are very fast! Thank you
