### ISSUE TITLE
[code formatter] 1.1.5.956 regressions 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#83]
before formatting
```
function ValueParts(DafaultValue, Value: Variant): Integer;
begin
  if VarType(DafaultValue) = varUString then
    Result := Max(Ceil(Length(string(Value)) / 3000), 1)
  else
    Result := 1;
end;
```

after formatting
```
function ValueParts(DafaultValue, Value: Variant): Integer;
begin
  if VarType(DafaultValue) = varUString then
    Result := Max(Ceil(Length(string(Value)) / 3000), 1)

  else
    Result := 1;
end;
```

same for else if, before formatting
```
function ValueParts(DafaultValue, Value: Variant): Integer;
begin
  if Item.Crypted = cvCrypt then
    Value := AES128Encrypt(Value)
  else if Item.Crypted= cvCompressAndCrypt then
  begin

  end;
end;
```

after formatting
```
function ValueParts(DafaultValue, Value: Variant): Integer;
begin
  if Item.Crypted = cvCrypt then
    Value := AES128Encrypt(Value)

  else if Item.Crypted= cvCompressAndCrypt then
  begin

  end;
end;
```

![image](https://user-images.githubusercontent.com/1270275/50587595-cd078100-0e7e-11e9-8ead-fb05b4c3ce2c.png)

**Comment by Sorien** [comment]
removed space before condition 
```
procedure a();
begin
  if Dialog('', '', ['', 'OK'], 0,
    TDialogIcon.tiError) = 0 then
  begin

  end;
end;
```
after formatting
```
procedure a();
begin
  if Dialog('', '', ['', 'OK'], 0,
    TDialogIcon.tiError)= 0 then
  begin

  end;
end;
```

**Comment by shanzhashu** [comment]
Oh, Do you check the new option "Keep User Line Break"?

**Comment by Sorien** [comment]
yep, there is screenshot of my actual settings in first post.

**Comment by shanzhashu** [comment]
See. these bugs come from the new option "Keep User Line Break."
Now "removes space" fixed, "else empty line" fixed, but the anonymous function indent problem are a little complex.

**Comment by Sorien** [comment]
anonymous methods ... ok
else and else if ... ok
space before condition ... ok

but noticed few more
```pascal
procedure Foo();
begin
  if a.TryGetValue(Id, b) then
  begin
    c.AddRange(b)
  end;
end;
```

after formatting
```pascal
procedure Foo();
begin
  if a.TryGetValue(Id, b) then
  begin
    c.AddRange(b)

  end;
end;
``` 

and 
```pascal
function Foo(): string;
begin
  Result := ''
end;
```

after formatting
```pascal
function Foo(): string;
begin
  Result := ''

end;
```

**Comment by shanzhashu** [comment]
Oh, additional empty lines. Now I fixed it.

**Comment by shanzhashu** [comment]
958 is ready for these bugs.

**Comment by Sorien** [comment]
fixed, thanks

**Comment by Sorien** [comment]
i found few more samples generating new lines though
```pascal
procedure a();
begin
  try
  finally
    Free
  end;
end;
```
and same with `except`
```pascal
procedure a();
begin
  try
  except
    Free
  end;
end;
```

after formatting
```pascal
procedure a();
begin
  try
  finally
    Free

  end;
end;
```

**Comment by shanzhashu** [comment]
Fixed again, including try except/finally end and case [else] end.

**Comment by Sorien** [comment]
as i see from commit logs you have disabled `Keep user linebreak` (that is most useful feature so far) will you reenable or should i close that issue? couse maybe i have few more regressions that i spotted but can't test last fixes.

**Comment by shanzhashu** [comment]
We hide this option for a publishing version. Now I re-enable this option in this dialog in 1.1.6.960 nightly-build version. We can continue to testing and fixing this options.
Thanks.

**Comment by Sorien** [comment]
ok, try and finally from examples above seems to be ok but there is few more 
```pascal
function a(): Boolean;
begin
  try
    Result := 1
  except
  end;
end;
```

after formatting
```
function a(): Boolean;
begin
  try
    Result := 1
  
  except
  end;
end;
```
same with finally  and repeat until
```
function a(): Boolean;
begin
  repeat
    Result := 1
  until True;
end;

**Comment by Sorien** [comment]
there is an extra new line for const array of records
```pascal
const
  t: array[1..2] of tt = ((
    a: 'a';
    b: 'b'
  ), (
    a: 'a';
    b: 'b'
  ));
```
after formatting
```pascal
const
  t: array[1..2] of tt = ((
    a: 'a';
    b: 'b'

  ), (
    a: 'a';
    b: 'b'

  ));
```

**Comment by shanzhashu** [comment]
Fixed and will be integrated to the next nightly-build version.

**Comment by shanzhashu** [comment]
961 comes at http://www.cnpack.org/downbuilds.php

**Comment by Sorien** [comment]
it looks ok, thx for fixes
