### ISSUE TITLE
Can't load exported configuration [CnWizards 1.1.6.959]

### ISSUE THREAD

**Issue by bozzy-gh** [cnpack/cnwizards#86]
I've just exported my configuration for a colleague who have a fresh install of Delphi and CnWizards, but he can't import it. I've tried reimporting it on my installation and I can't also. Also reinstalling after deleting all the configs won't help (I mean, the exported config can't be reimported).

**Comment by shanzhashu** [comment]
Oh, could you send your exported *.cnw file to me and let me check it?
And which version of Delphi do you use?

**Comment by bozzy-gh** [comment]
Yes, you'll find it attached to this mail.

I have Delphi 10.1, 10.2 and 10.3 installed on this PC, with CnWizards
installed on all three versions.
BTW, the config seems to be shared between the installations, right?

Il giorno gio 7 feb 2019 alle ore 15:47 Liu Xiao <notifications@github.com>
ha scritto:

**Comment by shanzhashu** [comment]
Oh the github email is only for notification. I can't get the reply.
Could you send the cnw file to master@cnpack.org?

Yes, all CnWizards Instances of Delphi share a common configuration defaultly, except we use command line switch to specify its particular configuration. 
See our help file.

**Comment by shanzhashu** [comment]
Do you get the error message "Can not import Registry"? If so, maybe you need run our CnConfigIO.exe as Administrator.

I'll add this hint at next version.

**Comment by bozzy-gh** [comment]
Oh, yes, the message is exactly that. I've now tried running with Admin
rights and it works. Sorry, my fault.

Thank you!

Il giorno lun 11 feb 2019 alle ore 16:12 Liu Xiao <notifications@github.com>
ha scritto:
