### ISSUE TITLE
[Code Formatter] keep line breaks and multidimensional const array

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#87]
i dont know if it's bug but formatter could respect user linebreaks in const arrays

```pascal 
function ConvertCertif(const Value: string): string;
const
  C: array[1..19] of array[1..2] of string = (('C650', '730'), ('N325', '325'), ('N380', '380'), ('N704', '704'),
    ('N705', '705'), ('N722', '722'), ('N730', '730'), ('N740', '740'), ('N820', '820'), ('N821', '821'),
    ('N823', '823'), ('N825', '825'), ('N864', '864'), ('N865', '865'), ('N935', '380'), ('N951', '951'),
    ('N952', '952'), ('N954', '954'), ('N955', '955'));
var
  I: Integer;
begin
end;
```

after formating
```pascal
function ConvertCertif(const Value: string): string;
const
  C: array[1..19] of array[1..2] of string = (('C650', '730'), ('N325', '325'), ('N380', '380'), ('N704', '704'), ('N705', '705'), ('N722',
    '722'), ('N730', '730'), ('N740', '740'), ('N820', '820'), ('N821', '821'), ('N823', '823'), ('N825', '825'), ('N864', '864'), ('N865', '865'), ('N935', '380'), ('N951', '951'), ('N952', '952'), ('N954', '954'), ('N955', '955'));
var
````

**Comment by checkdigits** [comment]
In a way I kind of think the formatter is doing the right thing when it *doesn’t* respect the user’s line breaks in the array. After all, doesn’t a code formatter explicitly exist to reformat line breaks and indentation to an overall homogenized standard?

I can see how the his might be undesirable or unhelpful though. The same would be true of arrays of string constants which are frequently manually laid out on single lines as they tend to be too long to read if they’re packed onto a couple of lines.

**Comment by shanzhashu** [comment]
In our design, this NEW keep line break option will keep the line break in "SOME CERTAIN" place such as in a simple statement and some const/var declaration, not for all places. It give user a chance to keep its own line break style if he already do much line break work in his code here.

But for some complex const/var declaration, there might be some potational problems if this option is on, we're trying to fix them.

If this options not checked(defaultly), we also provide auto line wrap options to avoid one line becoming too long.

**Comment by shanzhashu** [comment]
Please try our 963 nightly-build vesion?

http://www.cnpack.org/downbuilds.php

**Comment by Sorien** [comment]
seems to be working well, thx
