### ISSUE TITLE
[Code Formatter] Uses wrong wrapping with namespace

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#88]
I have auto wrap at 140
```pascal
uses
  A4578, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A234567800,
  A4578, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, AHCDEH.A2345678,
  A4578, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, AHCD.Adasfdafadsfasfadsfasfdfadfddfasfasfavsfdgsdf2345678,
  A4578, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678, A2345678000;
```
1st line has 140 chars and is not wrapped it ok
2nd line has unit with namespace prefix and length of 146 chars and is **not wrapped**
3rd is just some extreme scenario that ilustrates problem

**Comment by shanzhashu** [comment]
I think we treat the uses wrap as a simple way:
If exceed defined width(e.g. 140), but should NOT add line break for the reason "." should not be the line end, or "," should not be the line head, we'll continue output to current line until meet a "wrap-able" content. It will make current line longer than 140.

**Comment by Sorien** [comment]
hmm, im not so sure if its exactly like that 

```
uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics, Vcl.Controls, Vcl.Forms, Vcl.Dialogs, DB.ConnectionPool,
  DB.FirebirdConnection, Vcl.StdCtrls;
```
when i replace `.` with `_` it wraps correctly

```
uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics, Vcl.Controls, Vcl.Forms, Vcl.Dialogs,
  DB_ConnectionPool, DB.FirebirdConnection, Vcl.StdCtrls;
``` 

imo for uses section there should be no special treat for `.`

**Comment by shanzhashu** [comment]
The main cause is our grammar scanner makes WinAPI.Windows as 3 parts, not a complete identifier.

I'll try to find a easy way to make the unit name as a full identifier.

**Comment by shanzhashu** [comment]
970 nightly-build is ready for this way. Please try to verify it?

**Comment by Sorien** [comment]
i'll check it tomorrow at work

**Comment by Sorien** [comment]
yep, working correctly now, thx for fixes
