### ISSUE TITLE
Russian Translation Partly Missing

### ISSUE THREAD

**Issue by shanzhashu** [cnpack/cnwizards#9]
Some New Features now need UI Translation for Russian, Could anyone helps?
Below is the English items(\n means CRLF):

CnUsesCleaner=Welcome to Uses Units Cleaner!\n\nThis wizard can remove the unused reference units in 'uses' part.
CnIdeBRWizard=Welcome to IDE Config Backup Restore Tool!\n\nThis wizard, which can also run in stand-alone mode, can be used to backup/restore IDE Configurations of Delphi/C++Builder/BDS.
CnScriptWizard=Welcome to Script Wizard!\n\nScript Wizard provides scripting support of dynamic Pascal compiling and execution in IDE, including Script Window and Script Library. Script items can be called in menu item or triggered by some Events.
CnCodeFormatterWizard=Welcome to Code Formatter Wizard!\n\nThis Wizard can format code in IDE. Now only supports Pascal.

TCnCodeFormatterForm.Caption=Code Formatter Settings
TCnCodeFormatterForm.cbbBeginStyle.Items.Text=Next Line\nThis Line\n
TCnCodeFormatterForm.cbbKeywordStyle.Items.Text=Lower Case\nUpper Case\nUpper First Letter\nNo Change\n
TCnCodeFormatterForm.chkAutoWrap.Caption=Auto Wrap Line at:
TCnCodeFormatterForm.chkIgnoreArea.Caption=Do NOT Format Contents between {(*} and {*)}
TCnCodeFormatterForm.chkUsesSinglieLine.Caption=Single Line Mode for Every Uses Unit.
TCnCodeFormatterForm.grpAsm.Caption=ASM Settings
TCnCodeFormatterForm.grpCommon.Caption=Common Settings
TCnCodeFormatterForm.lblAsmHeadIndent.Caption=Line Head Indent:
TCnCodeFormatterForm.lblASMTab.Caption=Tab Width:
TCnCodeFormatterForm.lblBegin.Caption=Begin Style:
TCnCodeFormatterForm.lblKeyword.Caption=Keyword:
TCnCodeFormatterForm.lblNewLine.Caption=when Exceed:
TCnCodeFormatterForm.lblSpaceAfter.Caption=Space After Operator:
TCnCodeFormatterForm.lblSpaceBefore.Caption=Space Before Operator:
TCnCodeFormatterForm.lblTab.Caption=Tab Indent:
TCnCodeFormatterForm.tsPascal.Caption=Pascal

**Comment by schnider-ru** [comment]
CnUsesCleaner=Добро пожаловать в Мастер очистки неиспользуемых модулей!\n\nДанный мастер поможет удалить неиспользуемые модули в разделе 'uses'.
CnIdeBRWizard=Добро пожаловать в инструмент резервного копирования и восстановления настроек среды разработки!\n\nДанный мастер, который также может работать в автономном режиме, может быть использован для резервного копирования/восстановления конфигураций среды разработки Delphi/C++Builder/BDS.
CnScriptWizard=Добро пожаловать в Мастер Сценариев!\n\nДанный мастер обеспечивает поддержку динамической компиляции и выполнения сценариев в среде разработки, включая Окно Сценариев и Библиотеку сценариев. Различные сценарии могут быть вызваны по пункту меню или по некоторому событию.
CnCodeFormatterWizard=Добро пожаловать в Мастер форматирования кода!\n\nДанный мастер может форматировать код в редакторе среды разработки. Сейчас поддерживается только Pascal.

TCnCodeFormatterForm.Caption=Настройки форматирования кода
TCnCodeFormatterForm.cbbBeginStyle.Items.Text=Следующая строка\nТекущая строка\n
TCnCodeFormatterForm.cbbKeywordStyle.Items.Text=Нижний регистр\nВерхний регистр\nЗаглавная первая буква\nБез изменений\n
TCnCodeFormatterForm.chkAutoWrap.Caption=Автоматически выровнять строку на:
TCnCodeFormatterForm.chkIgnoreArea.Caption=НЕ форматировать содержимое между {(} и {)}
TCnCodeFormatterForm.chkUsesSinglieLine.Caption=По одному модулю на строку в разделе Uses.
TCnCodeFormatterForm.grpAsm.Caption=Настройки ASM
TCnCodeFormatterForm.grpCommon.Caption=Основные настройки
TCnCodeFormatterForm.lblAsmHeadIndent.Caption=Первый отступ в строкеLine Head Indent:
TCnCodeFormatterForm.lblASMTab.Caption=Ширина табуляции:
TCnCodeFormatterForm.lblBegin.Caption=Стиль Begin:
TCnCodeFormatterForm.lblKeyword.Caption=Ключевое слово:
TCnCodeFormatterForm.lblNewLine.Caption=когда превышает:
TCnCodeFormatterForm.lblSpaceAfter.Caption=Пробелов после оператора:
TCnCodeFormatterForm.lblSpaceBefore.Caption=Пробелов перед оператором:
TCnCodeFormatterForm.lblTab.Caption=Размер табуляции:
TCnCodeFormatterForm.tsPascal.Caption=Pascal

**Comment by shanzhashu** [comment]
Alexander, much thanks for your warm heart!
And, there're also some String Constants below in our Code Formatter Wizard, could you help to translate the values to Russian again?

SCnCodeFormatterWizardName=Code Formatter Wizard
SCnCodeFormatterWizardComment=Format Code
SCnCodeFormatterWizardMenuCaption=Code Formatter
SCnCodeFormatterWizardMenuHint=Code Formatter Wizard
SCnCodeFormatterWizardConfigCaption=&Options...
SCnCodeFormatterWizardConfigHint=&Options...
SCnCodeFormatterWizardFormatCurrentCaption=Format Current &File/Selection
SCnCodeFormatterWizardFormatCurrentHint=Format Current File or Selection
SCnCodeFormatterWizardErrLineWidth=Wrap Line Width Error.
SCnCodeFormatterWizardErrSelection=Can NOT Process Current Selection for Error Position.
SCnCodeFormatterErrUnknown=Unknown Error.
SCnCodeFormatterErrPascalFmt=Format Error(%d, %d): %s\n\nCurrent: ''%s''
SCnCodeFormatterErrPascalIdentExp=Identifier Expected.
SCnCodeFormatterErrPascalStringExp=String Expected.
SCnCodeFormatterErrPascalNumberExp=Number Expected.
SCnCodeFormatterErrPascalCharExp=Char Expected.
SCnCodeFormatterErrPascalSymbolExp=Symbol Expected.
SCnCodeFormatterErrPascalParseErr=Parse Error.
SCnCodeFormatterErrPascalInvalidBin=Invalid Binary.
SCnCodeFormatterErrPascalInvalidString=Invalid String.
SCnCodeFormatterErrPascalInvalidBookmark=Invalid Bookmark.
SCnCodeFormatterErrPascalLineTooLong=Line Too Long.
SCnCodeFormatterErrPascalEndCommentExp=Comment End Expected.
SCnCodeFormatterErrPascalNotSupport=Not Support.
SCnCodeFormatterErrPascalErrorDirective=Error Directive.
SCnCodeFormatterErrPascalNoMethodHeading=No Method Found.
SCnCodeFormatterErrPascalNoStructType=No Structured Type Found.
SCnCodeFormatterErrPascalNoTypedConstant=No Typed Constant Found.
SCnCodeFormatterErrPascalNoEqualColon=No Equal or Colon Found.
SCnCodeFormatterErrPascalNoDeclSection=No Declaration Selection Found.
SCnCodeFormatterErrPascalNoProcFunc=No Procedure or Function Found.
SCnCodeFormatterErrPascalUnknownGoal=Unknown Target Source File.
SCnCodeFormatterErrPascalErrorInterface=Interface Error.
SCnCodeFormatterErrPascalInvalidStatement=Invalid Statement.

**Comment by schnider-ru** [comment]
i think there is a typo in the line "SCnCodeFormatterErrPascalNoDeclSection=No Declaration **Selection** Found"

SCnCodeFormatterWizardName=Мастер форматирования кода
SCnCodeFormatterWizardComment=Форматировать код
SCnCodeFormatterWizardMenuCaption=Форматирование кода
SCnCodeFormatterWizardMenuHint=Мастер форматирования кода
SCnCodeFormatterWizardConfigCaption=&Настройки...
SCnCodeFormatterWizardConfigHint=&Настройки...
SCnCodeFormatterWizardFormatCurrentCaption=Форматировать текущий &Файл/Выделение
SCnCodeFormatterWizardFormatCurrentHint=Форматировать текущий файл или выделение
SCnCodeFormatterWizardErrLineWidth=Неправильное значение выравнивания строки.
SCnCodeFormatterWizardErrSelection=Невозможно определить место ошибки в текущем выделении.
SCnCodeFormatterErrUnknown=Неизвестная ошибка.
SCnCodeFormatterErrPascalFmt=Ошибка форматирования(%d, %d): %s\n\nЛексема: ''%s''
SCnCodeFormatterErrPascalIdentExp=Ожидается идентификатор.
SCnCodeFormatterErrPascalStringExp=Ожидается строка.
SCnCodeFormatterErrPascalNumberExp=Ожидается число.
SCnCodeFormatterErrPascalCharExp=Ожидается одиночный символ.
SCnCodeFormatterErrPascalSymbolExp=Ожидается символ.
SCnCodeFormatterErrPascalParseErr=Ошибка синтаксического разбора.
SCnCodeFormatterErrPascalInvalidBin=Недопустимые бинарные данные.
SCnCodeFormatterErrPascalInvalidString=Недопустимая строка.
SCnCodeFormatterErrPascalInvalidBookmark=Недействительная закладка.
SCnCodeFormatterErrPascalLineTooLong=Строка слишком длинная.
SCnCodeFormatterErrPascalEndCommentExp=Ожидается конец комментария.
SCnCodeFormatterErrPascalNotSupport=Не поддерживается.
SCnCodeFormatterErrPascalErrorDirective=Ошибочная директива.
SCnCodeFormatterErrPascalNoMethodHeading=Не найден метод.
SCnCodeFormatterErrPascalNoStructType=Не найден структурированный тип.
SCnCodeFormatterErrPascalNoTypedConstant=Не найдена типизированная константа.
SCnCodeFormatterErrPascalNoEqualColon=Не найдены знаки равно или двоеточие.
SCnCodeFormatterErrPascalNoDeclSection=Не найден раздел объявлений.
SCnCodeFormatterErrPascalNoProcFunc=Не найдена процедура или функция.
SCnCodeFormatterErrPascalUnknownGoal=Неизвестный тип (назначение) файла.
SCnCodeFormatterErrPascalErrorInterface=Неправильное описание интерфейса.
SCnCodeFormatterErrPascalInvalidStatement=Неправильный оператор.

**Comment by shanzhashu** [comment]
Thanks!

Section here is not a typo. It means a Declaration Segment in Pascal Unit. This word comes from Pascal Grammar Description.

We'll integrate your contribute. Thanks again.

**Comment by schnider-ru** [comment]
But there "selection", not "section"

**Comment by shanzhashu** [comment]
Oh. I made a 'BIG' mistake and messed up.

Now I correct it. Thanks for your reminder.

**Comment by schnider-ru** [comment]
![codeformatter_settings_ru](https://cloud.githubusercontent.com/assets/3140590/8598357/e5ba97d0-2662-11e5-8626-b6b957ba1d38.png)

**Comment by shanzhashu** [comment]
OK. I just copy it from above. "Line Head Indent" will be removed. But the label length problem are not easy to handle...

**Comment by schnider-ru** [comment]
"Line Head Indent" - It's my mistake, sorry.
Well, then I suggest shorter versions of the translation:
TCnCodeFormatterForm.chkAutoWrap.Caption=Перенос строки на:
TCnCodeFormatterForm.lblNewLine.Caption=если свыше:

**Comment by shanzhashu** [comment]
OK. I commit this shorter change.
Thanks.

**Comment by shanzhashu** [comment]
I send a mail to schnider.ru@gmail.com for we have 3 new items to translate. Could you check it and help us?

**Comment by schnider-ru** [comment]
SCnMenuEnableThumbnailCaption=Окно предварительного просмотра
TCnSrcEditorEnhanceForm.chkShowThumbnail.Caption=Показывать всплывающую подсказку когда курсор над вертикальной полосой прокрутки
TCnUsesCleanerForm.chkProcessDependencies.Caption=Включая неявно используемые модули

I should also note that the word “Indirect**l**y” has a typo.

**Comment by shanzhashu** [comment]
Oh. I fix this typo.

And thank you very much.

**Comment by shanzhashu** [comment]
We have a new feature in source highlight wizard: Show line positions of current identifiers at Left Gutter of Editor. Now we add a checkbox in Source Highlight Setting Dialog. Could you help to translate this item to Russian?

TCnSourceHighlightForm.chkShowLinePosAtGutter.Caption=Show Current Identifier Positions at Gutter.

**Comment by schnider-ru** [comment]
TCnSourceHighlightForm.chkShowLinePosAtGutter.Caption=Показывать позиции текущего идентификатора в левом поле редактора.

This translation too long and does not fit to label, but in Russian language there is no specific word for "editor gutter"

**Comment by shanzhashu** [comment]
Thanks. So, could we use "Line Number Bar" instead of Gutter?

**Comment by schnider-ru** [comment]
TCnSourceHighlightForm.chkShowLinePosAtGutter.Caption=Показывать позиции текущего идентификатора на номерах строк.

A little bit shorter...

**Comment by shanzhashu** [comment]
A new option in Code Formatter added. It allows correct the Case of identifiers in Source using IDE compiler symbols in Input Helper. Could you help to translate this sentence into Russian?

TCnCodeFormatterForm.chkUseIDESymbols.Caption=Use IDE Internal Symbols to Correct Identifiers.

**Comment by schnider-ru** [comment]
TCnCodeFormatterForm.chkUseIDESymbols.Caption=Использовать внутренние символы среды для коррекции идентификаторов.

**Comment by shanzhashu** [comment]
We add 3 options in Setting Dialog of Source Editor Enhancement. Could you help to translate these to Russian?

TCnSrcEditorEnhanceForm.chkGutterClickSelectLine.Caption=Single Click to Select One Line in Editor.
TCnSrcEditorEnhanceForm.chkGutterDblClickToggleBookmark.Caption=Double Click to Toggle Bookmark in Editor.
TCnSrcEditorEnhanceForm.chkGutterDragSelectLines.Caption=Drag to Select Multi-Lines in Editor(N.A. for BDS).

Thanks.

**Comment by schnider-ru** [comment]
TCnSrcEditorEnhanceForm.chkGutterClickSelectLine.Caption=Один щелчок для выбора строки в редакторе.
TCnSrcEditorEnhanceForm.chkGutterDblClickToggleBookmark.Caption=Двойной щелчок для переключения закладки в редакторе.
TCnSrcEditorEnhanceForm.chkGutterDragSelectLines.Caption=Тянуть для выбора нескольких строк в редакторе(Не для BDS).

**Comment by shanzhashu** [comment]
Thanks. ;-)

**Comment by shanzhashu** [comment]
In our uses cleaner, we add an option to process the result when meeting huge project files. Please help to translate it to Russian?

TCnUsesCleanerForm.chkSaveAndClose.Caption=Auto Save/Close Unopened Files(For Huge Project but Can't Undo).

**Comment by schnider-ru** [comment]
TCnUsesCleanerForm.chkSaveAndClose.Caption=Автосохранение/Закрывать неоткрытые файлы(Для больших проектов, без отмены)

**Comment by shanzhashu** [comment]
Thanks!

**Comment by shanzhashu** [comment]
Hi, there's  a new Item for a ComboBox in our Code Formatter Wizard. This option is used to control the Compiler Directives' processing mode. Could you help to translate it in to Russian?

TCnCodeFormatterForm.cbbDirectiveMode.Items.Text=Treat as Comment<BR>Only Processing First Branch<BR>

**Comment by schnider-ru** [comment]
TCnCodeFormatterForm.cbbDirectiveMode.Items.Text=Считать комментарием
Обработать только первую ветвь

**Comment by shanzhashu** [comment]
Thanks and Happy Middle-Autumn Festival!
