### ISSUE TITLE
Editor window tab set is not anchored

### ISSUE THREAD

**Issue by DelphiWorlds** [cnpack/cnwizards#90]
When docked windows are re-sized they can end up covering the editor window tab set (see image)

![image](https://user-images.githubusercontent.com/22670829/53723745-4855d500-3eb8-11e9-8437-ff15a4d6ff1e.png)

Unfortunately, the CnLocalHistoryWizard cannot be disabled to get around this problem

**Comment by shanzhashu** [comment]
In fact, the CnLocalHistoryWizard.pas is  a half-developed wizard and not integrated in our CnWizards Dll.

**Comment by shanzhashu** [comment]
I guess you maybe means our EditorTabSetHook feature caused this problem? I'll check it.

**Comment by DelphiWorlds** [comment]
Does something other than CnLocalHistoryWizard use EditorTabSetHook? Regardless, it appears EditorTabSetHook is the only thing that does something to the ViewBar component on the editor window, so I'm assuming that it is the cause.

**Comment by shanzhashu** [comment]
For temp solution, we can just disable "FeedReader Wizard" to disable EditorTabSetHook indirectly. After restarging IDE it should be OK.

**Comment by DelphiWorlds** [comment]
Thanks!!
