### ISSUE TITLE
[Code Formatter] changes Contains to contains 

### ISSUE THREAD

**Issue by Sorien** [cnpack/cnwizards#91]
```pascal
interface
type
  TFoo = class
    function Contains(): Boolean;
  end;

implementation

function TFoo.Contains: Boolean;
begin

end;
```
after format

```pascal
interface
type
  TFoo = class
    function contains(): Boolean;
  end;

implementation

function TFoo.contains: Boolean;
begin

end;
```

**Comment by Sorien** [comment]
"Use IDE Internal symbols to correct identifiers" is disabled in settings

**Comment by shanzhashu** [comment]
Oh. contains is a keyword in dpk file so we treat it as a keyword.
I'll try to distinguish them between dpk or normal pascal file.

**Comment by shanzhashu** [comment]
Now we only treat requires/contains as Keywords in Package source file, not in normal Pascal file.

**Comment by shanzhashu** [comment]
968 nightly-build version integrated this fix.

http://www.cnpack.org/downbuilds.php?lang=zh-cn

**Comment by Sorien** [comment]
it's fixed, thx
