### ISSUE TITLE
在对象内声明的常量，自动完成无法提示

### ISSUE THREAD

**Issue by unjiang** [cnpack/cnwizards#95]
为了不混淆常量，我在数据库模块中声明了一些本模块专用常量，在其他单元引用了这个数据模块后，声明DataWenBen为TDataWenBen，输入“DataWenBen.”后无法出现那些存在的常量标识符。
 Delphi XE7 Version 21.0.17707.5020 
cnpack Ver: 1.1.6.959 Build 2019.01.14

type
  TDataWenBen = class(TDataModule)
    var
      FDConnection1: TFDConnection;
      FDQuery1: TFDQuery;
      FDPhysSQLiteDriverLink1: TFDPhysSQLiteDriverLink;
      FDGUIxWaitCursor1: TFDGUIxWaitCursor;
      DataSource1: TDataSource;
    procedure DataModuleCreate(Sender: TObject);
    procedure FDQuery1BeforePost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    { Public declarations }
    const
      strDBFile = 'output\WenBen.db';
      strTable = 'wbWen';
      strColID = 'wbID';
      strColTitle = 'wbTitle';
      strColContent = 'wbContent';
      strColDate = 'wbDate';
  end;

**Comment by shanzhashu** [comment]
比较麻烦。代码输入助手的大部分符号列表来自IDE的实时编译解析，的确存在部分符号缺失的情况，目前还没有什么有效的方法去弥补。

**Comment by unjiang** [comment]
看来只好写到对象外面了，使用的时候前面加上单元名。

**Comment by shanzhashu** [comment]
做了一些补救，尝试一下984每日构建版？
http://www.cnpack.org/downbuilds.php

**Comment by unjiang** [comment]
试了一下，完美的解决了对象内常量提示问题。谢谢！
