### ISSUE TITLE
DX10.3Rio - not work HideOrigToolbar option

### ISSUE THREAD

**Issue by pult** [cnpack/cnwizards#97]
DX10.3Rio - not work HideOrigToolbar option
[HKEY_CURRENT_USER\Software\CnPack\CnWizards\CnSrcEditorEnhance\Misc]
"HideOrigToolbar"="1"

After first click on code editor original toolbar showing.

**Comment by shanzhashu** [comment]
Which CnWizards version do you use? Could you try out latest nightly-build version 983 to check it ?

http://www.cnpack.org/downbuilds.php

**Comment by pult** [comment]
983 - partially works :

- "project * .dpr" - does not work
- "Winapi.Messages.pas" - Not working
- project unit / form - works. But it stops working after choosing another module. After double press F12 - works.

**Comment by shanzhashu** [comment]
Seems in 10.3, some EditorView Change notification missed, I'll add some workaround to it.

**Comment by shanzhashu** [comment]
Please try our 984 nightly-build?

**Comment by pult** [comment]
984 not presented at it moment

**Comment by shanzhashu** [comment]
Oh, missing.

Now 984 is on our nightly-build page.

**Comment by pult** [comment]
984 is worked. Thanks!
