### ISSUE TITLE
[Code Editor]: there is no ability to turn off autocompletion after pressed "point"

### ISSUE THREAD

**Issue by pult** [cnpack/cnwizards#98]
[Code Editor]: there is no ability to turn off autocompletion after pressed "point"

**Comment by pult** [comment]
Options:

[HKEY_CURRENT_USER\Software\CnPack\CnWizards\CnInputHelper]
"Width"=dword:0000012c
"Height"=dword:0000005f
"Font"="Tahoma,8,,0,clWindowText,DEFAULT_CHARSET"
"DispButtons"="1"
"AutoPopup"="1"
"ListOnlyAtLeastLetter"=dword:00000001
"DispOnlyAtLeastKey"=dword:00000002
"DispKindSet"=dword:0007ffff
"SortKind"=dword:00000000
"MatchAnyWhere"="1"
"AutoAdjustScope"="1"
"RemoveSame"="1"
"DispDelay"=dword:000000fa
"EnableAutoSymbols"="0"
"SpcComplete"="0"
"IgnoreSpc"="0"
"AutoInsertEnter"="1"
"AutoCompParam"="1"
"SmartDisplay"="1"
"OutputStyle"=dword:00000000
"KeywordStyle"=dword:00000000
"SelMidMatchByEnterOnly"="1"
"CheckImmRun"="0"
"DispOnIDECompDisabled"="1"
"TabComplete"="0"
"CompleteCharSet"=""

**Comment by shanzhashu** [comment]
Do you means "turn off IDE's code completion" or "turn off CnWizards Input Helper"?

**Comment by pult** [comment]
Build 1.1.8.984 - I do not feel the problem anymore. Thanks!
