### ISSUE TITLE
[Code Formatter] - Can't format Anonymous Methods

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [cnpack/cnwizards#99]
**Changes indent.**

Before:

        for s in TDirectory.GetFiles('', '',
         function(const Path: string; const SearchRec: TSearchRec): Boolean
         begin
           Result := True;
         end)
        do
          Result := True;

After:

        for s in TDirectory.GetFiles('', '',
      function(const Path: string; const SearchRec: TSearchRec): Boolean
      begin
        Result := True;
      end) do
          Result := True;

**Adds blank lines after each reformat.**

Before:

        {(*}
        for s in TDirectory.GetFiles('', '',
         function(const Path: string; const SearchRec: TSearchRec): Boolean
         begin
           Result := True;
         end)
        do
          Result := True;
        {(*}

After:

        {(*}
        for s in TDirectory.GetFiles('', '',
    
    function(const Path: string; const SearchRec: TSearchRec): Boolean
         begin
           Result := True;
         end)
        do
          Result := True;
        {(*}
[test.zip (example unit)](https://github.com/cnpack/cnwizards/files/3439353/test.zip)

**Comment by shanzhashu** [comment]
Thanks for your report. Now I try to fix the problems and build a new nightly-build version 982 of CnWizards in http://www.cnpack.org/downbuilds.php    Could you try it?

**Comment by Ze2QvoQxxKeu** [comment]
Big thanks, all works.
